// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: manned.sql

package timeseries

import (
	"context"
	"encoding/json"
	"time"
)

const countMannedTracksInWindow = `-- name: CountMannedTracksInWindow :one
SELECT count(*)::bigint AS n FROM manned_tracks
WHERE captured_at >= $1 AND captured_at < $2
`

type CountMannedTracksInWindowParams struct {
	FromTs time.Time
	ToTs   time.Time
}

func (q *Queries) CountMannedTracksInWindow(ctx context.Context, arg CountMannedTracksInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMannedTracksInWindow, arg.FromTs, arg.ToTs)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const feedProductsByClient = `-- name: FeedProductsByClient :many
SELECT at, client_id, tracks_sent, tracks_relevant, degraded, policy_version
FROM feed_products
WHERE client_id = $1 AND at >= $2 AND at < $3
ORDER BY at
LIMIT $4
`

type FeedProductsByClientParams struct {
	ClientID string
	FromTs   time.Time
	ToTs     time.Time
	PageSize int32
}

func (q *Queries) FeedProductsByClient(ctx context.Context, arg FeedProductsByClientParams) ([]FeedProduct, error) {
	rows, err := q.db.Query(ctx, feedProductsByClient,
		arg.ClientID,
		arg.FromTs,
		arg.ToTs,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeedProduct{}
	for rows.Next() {
		var i FeedProduct
		if err := rows.Scan(
			&i.At,
			&i.ClientID,
			&i.TracksSent,
			&i.TracksRelevant,
			&i.Degraded,
			&i.PolicyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFeedProduct = `-- name: InsertFeedProduct :exec
INSERT INTO feed_products (at, client_id, tracks_sent, tracks_relevant, degraded, policy_version)
VALUES (clock_timestamp(), $1, $2, $3,
        $4, $5)
`

type InsertFeedProductParams struct {
	ClientID       string
	TracksSent     int32
	TracksRelevant int32
	Degraded       []string
	PolicyVersion  int64
}

func (q *Queries) InsertFeedProduct(ctx context.Context, arg InsertFeedProductParams) error {
	_, err := q.db.Exec(ctx, insertFeedProduct,
		arg.ClientID,
		arg.TracksSent,
		arg.TracksRelevant,
		arg.Degraded,
		arg.PolicyVersion,
	)
	return err
}

const mannedTracksByICAO24 = `-- name: MannedTracksByICAO24 :many
SELECT captured_at, ts, rx_ts, time_source, backlog, adapter_id, icao24, callsign,
       ST_Y(geom)::double precision AS lat_deg, ST_X(geom)::double precision AS lon_deg,
       alt_pressure_m, alt_wgs84_m, gs_ms, track_deg, vrate_ms, emergency, squawk,
       source_class, quality, relevant, policy_version
FROM manned_tracks
WHERE icao24 = $1 AND captured_at >= $2 AND captured_at < $3
ORDER BY captured_at
LIMIT $4
`

type MannedTracksByICAO24Params struct {
	Icao24   string
	FromTs   time.Time
	ToTs     time.Time
	PageSize int32
}

type MannedTracksByICAO24Row struct {
	CapturedAt    time.Time
	Ts            time.Time
	RxTs          time.Time
	TimeSource    string
	Backlog       bool
	AdapterID     string
	Icao24        string
	Callsign      *string
	LatDeg        float64
	LonDeg        float64
	AltPressureM  *float64
	AltWgs84M     *float64
	GsMs          *float64
	TrackDeg      *float64
	VrateMs       *float64
	Emergency     *bool
	Squawk        *string
	SourceClass   string
	Quality       json.RawMessage
	Relevant      bool
	PolicyVersion int64
}

// One aircraft's samples in [from_ts, to_ts), oldest first, bounded.
func (q *Queries) MannedTracksByICAO24(ctx context.Context, arg MannedTracksByICAO24Params) ([]MannedTracksByICAO24Row, error) {
	rows, err := q.db.Query(ctx, mannedTracksByICAO24,
		arg.Icao24,
		arg.FromTs,
		arg.ToTs,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MannedTracksByICAO24Row{}
	for rows.Next() {
		var i MannedTracksByICAO24Row
		if err := rows.Scan(
			&i.CapturedAt,
			&i.Ts,
			&i.RxTs,
			&i.TimeSource,
			&i.Backlog,
			&i.AdapterID,
			&i.Icao24,
			&i.Callsign,
			&i.LatDeg,
			&i.LonDeg,
			&i.AltPressureM,
			&i.AltWgs84M,
			&i.GsMs,
			&i.TrackDeg,
			&i.VrateMs,
			&i.Emergency,
			&i.Squawk,
			&i.SourceClass,
			&i.Quality,
			&i.Relevant,
			&i.PolicyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const schemaVersion = `-- name: SchemaVersion :one

SELECT version_id FROM goose_db_version_timeseries
WHERE is_applied ORDER BY id DESC LIMIT 1
`

// WP-1: the timeseries reads and the feed record. The bulk insert of
// manned_tracks is store.Writer (CopyFrom into a staging table), not a
// generated query.
func (q *Queries) SchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, schemaVersion)
	var version_id int64
	err := row.Scan(&version_id)
	return version_id, err
}
