// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package timeseries

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type FeedProduct struct {
	At             time.Time
	ClientID       string
	TracksSent     int32
	TracksRelevant int32
	Degraded       []string
	PolicyVersion  int64
}

type GooseDbVersionTimeseries struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    pgtype.Timestamp
}

type MannedTrack struct {
	CapturedAt    time.Time
	Ts            time.Time
	RxTs          time.Time
	TimeSource    string
	Backlog       bool
	AdapterID     string
	Icao24        string
	Callsign      *string
	Geom          interface{}
	AltPressureM  *float64
	AltWgs84M     *float64
	GsMs          *float64
	TrackDeg      *float64
	VrateMs       *float64
	Emergency     *bool
	Squawk        *string
	SourceClass   string
	Quality       json.RawMessage
	Relevant      bool
	PolicyVersion int64
}
