// Package cispclient is the generated Go client and models of the CISP's
// national API at the commit api/clients/SOURCE pins (cisp.yaml): the
// publication, heartbeat and read calls this system makes, and the
// cis/change/v1, cis/restriction/v1 and cis/ussp_list/v1 bodies. Never
// edited by hand; regenerated by `make generate`.
package cispclient

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.8.0 -config oapi-codegen.yaml -o cispclient.gen.go ../cisp.yaml
