// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adapters.sql

package relational

import (
	"context"
	"encoding/json"
	"time"
)

const adapterByID = `-- name: AdapterByID :one
SELECT id, kind, display_name, source_class, config, status, last_frame_at, last_status_at, counters FROM adapters WHERE id = $1
`

func (q *Queries) AdapterByID(ctx context.Context, id string) (Adapter, error) {
	row := q.db.QueryRow(ctx, adapterByID, id)
	var i Adapter
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.SourceClass,
		&i.Config,
		&i.Status,
		&i.LastFrameAt,
		&i.LastStatusAt,
		&i.Counters,
	)
	return i, err
}

const listAdapters = `-- name: ListAdapters :many
SELECT id, kind, display_name, source_class, config, status, last_frame_at, last_status_at, counters FROM adapters ORDER BY id LIMIT $1
`

func (q *Queries) ListAdapters(ctx context.Context, pageSize int32) ([]Adapter, error) {
	rows, err := q.db.Query(ctx, listAdapters, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Adapter{}
	for rows.Next() {
		var i Adapter
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.DisplayName,
			&i.SourceClass,
			&i.Config,
			&i.Status,
			&i.LastFrameAt,
			&i.LastStatusAt,
			&i.Counters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAdapterStatus = `-- name: SetAdapterStatus :execrows
UPDATE adapters
SET status = $1, last_frame_at = $2,
    last_status_at = clock_timestamp(), counters = $3
WHERE id = $4
`

type SetAdapterStatusParams struct {
	Status      string
	LastFrameAt *time.Time
	Counters    json.RawMessage
	ID          string
}

func (q *Queries) SetAdapterStatus(ctx context.Context, arg SetAdapterStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAdapterStatus,
		arg.Status,
		arg.LastFrameAt,
		arg.Counters,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAdapter = `-- name: UpsertAdapter :one

INSERT INTO adapters (id, kind, display_name, source_class, config)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    kind = EXCLUDED.kind, display_name = EXCLUDED.display_name,
    source_class = EXCLUDED.source_class, config = EXCLUDED.config
RETURNING id, kind, display_name, source_class, config, status, last_frame_at, last_status_at, counters
`

type UpsertAdapterParams struct {
	ID          string
	Kind        string
	DisplayName string
	SourceClass string
	Config      json.RawMessage
}

// WP-1: the adapter registry.
func (q *Queries) UpsertAdapter(ctx context.Context, arg UpsertAdapterParams) (Adapter, error) {
	row := q.db.QueryRow(ctx, upsertAdapter,
		arg.ID,
		arg.Kind,
		arg.DisplayName,
		arg.SourceClass,
		arg.Config,
	)
	var i Adapter
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.SourceClass,
		&i.Config,
		&i.Status,
		&i.LastFrameAt,
		&i.LastStatusAt,
		&i.Counters,
	)
	return i, err
}
