// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package relational

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const challengeForUpdate = `-- name: ChallengeForUpdate :one
SELECT token_hash, user_id, created_at, expires_at, attempts, used_at, remote_ip FROM login_challenges WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) ChallengeForUpdate(ctx context.Context, tokenHash string) (LoginChallenge, error) {
	row := q.db.QueryRow(ctx, challengeForUpdate, tokenHash)
	var i LoginChallenge
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Attempts,
		&i.UsedAt,
		&i.RemoteIp,
	)
	return i, err
}

const clearLockout = `-- name: ClearLockout :exec
DELETE FROM login_lockouts WHERE username = $1
`

func (q *Queries) ClearLockout(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, clearLockout, username)
	return err
}

const clientSeen = `-- name: ClientSeen :one
SELECT client_id, system, issuer, mtls_subject, first_seen_at, last_seen_at, scopes_seen FROM oauth_clients_seen WHERE client_id = $1
`

func (q *Queries) ClientSeen(ctx context.Context, clientID string) (OauthClientsSeen, error) {
	row := q.db.QueryRow(ctx, clientSeen, clientID)
	var i OauthClientsSeen
	err := row.Scan(
		&i.ClientID,
		&i.System,
		&i.Issuer,
		&i.MtlsSubject,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ScopesSeen,
	)
	return i, err
}

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*) FROM users WHERE role = 'admin' AND status = 'active'
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChallengeAttempt = `-- name: CountChallengeAttempt :exec
UPDATE login_challenges SET attempts = attempts + 1 WHERE token_hash = $1
`

func (q *Queries) CountChallengeAttempt(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, countChallengeAttempt, tokenHash)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredChallenges = `-- name: DeleteExpiredChallenges :execrows
DELETE FROM login_challenges WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredChallenges(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredChallenges, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM user_sessions WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleLockouts = `-- name: DeleteStaleLockouts :execrows
DELETE FROM login_lockouts
WHERE updated_at < $1 AND (locked_until IS NULL OR locked_until < $2)
`

type DeleteStaleLockoutsParams struct {
	Before time.Time
	Now    *time.Time
}

// A lockout row untouched since before and holding no lock.
func (q *Queries) DeleteStaleLockouts(ctx context.Context, arg DeleteStaleLockoutsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleLockouts, arg.Before, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserMFA = `-- name: DeleteUserMFA :execrows
DELETE FROM user_mfa WHERE user_id = $1
`

func (q *Queries) DeleteUserMFA(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserMFA, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureLockout = `-- name: EnsureLockout :exec
INSERT INTO login_lockouts (username, updated_at) VALUES ($1, $2)
ON CONFLICT (username) DO NOTHING
`

type EnsureLockoutParams struct {
	Username string
	At       time.Time
}

func (q *Queries) EnsureLockout(ctx context.Context, arg EnsureLockoutParams) error {
	_, err := q.db.Exec(ctx, ensureLockout, arg.Username, arg.At)
	return err
}

const insertChallenge = `-- name: InsertChallenge :exec
INSERT INTO login_challenges (token_hash, user_id, created_at, expires_at, remote_ip)
VALUES ($1, $2, $3, $4, $5)
`

type InsertChallengeParams struct {
	TokenHash string
	UserID    uuid.UUID
	At        time.Time
	ExpiresAt time.Time
	RemoteIp  string
}

func (q *Queries) InsertChallenge(ctx context.Context, arg InsertChallengeParams) error {
	_, err := q.db.Exec(ctx, insertChallenge,
		arg.TokenHash,
		arg.UserID,
		arg.At,
		arg.ExpiresAt,
		arg.RemoteIp,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO user_sessions (jti, user_id, role, issued_at, expires_at, last_seen_at, remote_ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $4,
        $6, $7)
`

type InsertSessionParams struct {
	Jti       string
	UserID    uuid.UUID
	Role      string
	IssuedAt  time.Time
	ExpiresAt time.Time
	RemoteIp  string
	UserAgent string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.Jti,
		arg.UserID,
		arg.Role,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.RemoteIp,
		arg.UserAgent,
	)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (username, password_hash, role, created_at, created_by, updated_at, updated_by)
VALUES ($1, $2, $3, $4, $5, $4, $5)
RETURNING id, username, password_hash, role, status, oidc_subject, created_at, created_by, updated_at, updated_by, last_login_at
`

type InsertUserParams struct {
	Username     string
	PasswordHash string
	Role         string
	At           time.Time
	Actor        string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.At,
		arg.Actor,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.LastLoginAt,
	)
	return i, err
}

const listLiveSessions = `-- name: ListLiveSessions :many
SELECT jti, user_id, role, expires_at FROM user_sessions
WHERE revoked_at IS NULL AND expires_at > clock_timestamp()
  AND last_seen_at > clock_timestamp() - make_interval(secs => $1::double precision)
ORDER BY jti
LIMIT $2
`

type ListLiveSessionsParams struct {
	IdleS    float64
	PageSize int32
}

type ListLiveSessionsRow struct {
	Jti       string
	UserID    uuid.UUID
	Role      string
	ExpiresAt time.Time
}

// WP-6: the live sessions projected to KV sessions_live (docs/PLAN.md
// section 15 row 21): not revoked, not expired and used within the idle
// timeout, all on the database clock; bounded, the caller asks for one
// more than it takes to know when it was cut.
func (q *Queries) ListLiveSessions(ctx context.Context, arg ListLiveSessionsParams) ([]ListLiveSessionsRow, error) {
	rows, err := q.db.Query(ctx, listLiveSessions, arg.IdleS, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveSessionsRow{}
	for rows.Next() {
		var i ListLiveSessionsRow
		if err := rows.Scan(
			&i.Jti,
			&i.UserID,
			&i.Role,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, role, status, oidc_subject, created_at, created_by, updated_at, updated_by, last_login_at FROM users ORDER BY username LIMIT $1
`

func (q *Queries) ListUsers(ctx context.Context, maxRows int32) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.OidcSubject,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockoutByUsername = `-- name: LockoutByUsername :one
SELECT username, failures, locked_until, updated_at FROM login_lockouts WHERE username = $1
`

func (q *Queries) LockoutByUsername(ctx context.Context, username string) (LoginLockout, error) {
	row := q.db.QueryRow(ctx, lockoutByUsername, username)
	var i LoginLockout
	err := row.Scan(
		&i.Username,
		&i.Failures,
		&i.LockedUntil,
		&i.UpdatedAt,
	)
	return i, err
}

const lockoutForUpdate = `-- name: LockoutForUpdate :one
SELECT username, failures, locked_until, updated_at FROM login_lockouts WHERE username = $1 FOR UPDATE
`

func (q *Queries) LockoutForUpdate(ctx context.Context, username string) (LoginLockout, error) {
	row := q.db.QueryRow(ctx, lockoutForUpdate, username)
	var i LoginLockout
	err := row.Scan(
		&i.Username,
		&i.Failures,
		&i.LockedUntil,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE user_sessions SET revoked_at = $1, revoke_reason = $2
WHERE jti = $3 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	At     *time.Time
	Reason *string
	Jti    string
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.At, arg.Reason, arg.Jti)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessions = `-- name: RevokeUserSessions :many
UPDATE user_sessions SET revoked_at = $1, revoke_reason = $2
WHERE user_id = $3 AND revoked_at IS NULL
RETURNING jti
`

type RevokeUserSessionsParams struct {
	At     *time.Time
	Reason *string
	UserID uuid.UUID
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, revokeUserSessions, arg.At, arg.Reason, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var jti string
		if err := rows.Scan(&jti); err != nil {
			return nil, err
		}
		items = append(items, jti)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionWithClock = `-- name: SessionWithClock :one
SELECT s.jti, s.user_id, s.role, s.issued_at, s.expires_at, s.last_seen_at, s.revoked_at, s.revoke_reason, s.remote_ip, s.user_agent, clock_timestamp()::timestamptz AS db_now FROM user_sessions s WHERE s.jti = $1
`

type SessionWithClockRow struct {
	Jti          string
	UserID       uuid.UUID
	Role         string
	IssuedAt     time.Time
	ExpiresAt    time.Time
	LastSeenAt   time.Time
	RevokedAt    *time.Time
	RevokeReason *string
	RemoteIp     string
	UserAgent    string
	DbNow        time.Time
}

// The session row and the database clock to judge it by.
func (q *Queries) SessionWithClock(ctx context.Context, jti string) (SessionWithClockRow, error) {
	row := q.db.QueryRow(ctx, sessionWithClock, jti)
	var i SessionWithClockRow
	err := row.Scan(
		&i.Jti,
		&i.UserID,
		&i.Role,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.RemoteIp,
		&i.UserAgent,
		&i.DbNow,
	)
	return i, err
}

const setLockout = `-- name: SetLockout :exec
UPDATE login_lockouts SET failures = $1, locked_until = $2, updated_at = $3
WHERE username = $4
`

type SetLockoutParams struct {
	Failures    int32
	LockedUntil *time.Time
	At          time.Time
	Username    string
}

func (q *Queries) SetLockout(ctx context.Context, arg SetLockoutParams) error {
	_, err := q.db.Exec(ctx, setLockout,
		arg.Failures,
		arg.LockedUntil,
		arg.At,
		arg.Username,
	)
	return err
}

const setUserStatus = `-- name: SetUserStatus :one
UPDATE users SET status = $1, updated_at = $2, updated_by = $3
WHERE id = $4
RETURNING id, username, password_hash, role, status, oidc_subject, created_at, created_by, updated_at, updated_by, last_login_at
`

type SetUserStatusParams struct {
	Status string
	At     time.Time
	Actor  string
	ID     uuid.UUID
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserStatus,
		arg.Status,
		arg.At,
		arg.Actor,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.LastLoginAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE user_sessions SET last_seen_at = clock_timestamp()
WHERE jti = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchSession(ctx context.Context, jti string) error {
	_, err := q.db.Exec(ctx, touchSession, jti)
	return err
}

const touchUserLogin = `-- name: TouchUserLogin :exec
UPDATE users SET last_login_at = $1 WHERE id = $2
`

type TouchUserLoginParams struct {
	At *time.Time
	ID uuid.UUID
}

func (q *Queries) TouchUserLogin(ctx context.Context, arg TouchUserLoginParams) error {
	_, err := q.db.Exec(ctx, touchUserLogin, arg.At, arg.ID)
	return err
}

const upsertClientSeen = `-- name: UpsertClientSeen :exec
INSERT INTO oauth_clients_seen (client_id, system, issuer, mtls_subject, first_seen_at, last_seen_at, scopes_seen)
VALUES ($1, $2, $3, $4, $5,
        $6, (SELECT coalesce(array_agg(s ORDER BY s), '{}') FROM (SELECT DISTINCT unnest($7::text[]) AS s ORDER BY 1 LIMIT 64) n))
ON CONFLICT (client_id) DO UPDATE SET
    system        = coalesce(EXCLUDED.system, oauth_clients_seen.system),
    issuer        = EXCLUDED.issuer,
    mtls_subject  = coalesce(EXCLUDED.mtls_subject, oauth_clients_seen.mtls_subject),
    first_seen_at = least(oauth_clients_seen.first_seen_at, EXCLUDED.first_seen_at),
    last_seen_at  = greatest(oauth_clients_seen.last_seen_at, EXCLUDED.last_seen_at),
    scopes_seen   = (SELECT coalesce(array_agg(s ORDER BY s), '{}')
                     FROM (SELECT DISTINCT unnest(oauth_clients_seen.scopes_seen || EXCLUDED.scopes_seen) AS s ORDER BY 1 LIMIT 64) m)
`

type UpsertClientSeenParams struct {
	ClientID    string
	System      *string
	Issuer      string
	MtlsSubject *string
	FirstSeenAt time.Time
	LastSeenAt  time.Time
	Scopes      []string
}

// First and last seen, the subject of the client certificate when one
// was bound, and the union of the scopes seen, capped at 64.
func (q *Queries) UpsertClientSeen(ctx context.Context, arg UpsertClientSeenParams) error {
	_, err := q.db.Exec(ctx, upsertClientSeen,
		arg.ClientID,
		arg.System,
		arg.Issuer,
		arg.MtlsSubject,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.Scopes,
	)
	return err
}

const upsertUserMFA = `-- name: UpsertUserMFA :exec
INSERT INTO user_mfa (user_id, key_id, secret_enc, enrolled_at, last_step, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE SET
    key_id = EXCLUDED.key_id, secret_enc = EXCLUDED.secret_enc, enrolled_at = EXCLUDED.enrolled_at,
    last_step = EXCLUDED.last_step, updated_at = EXCLUDED.updated_at
`

type UpsertUserMFAParams struct {
	UserID     uuid.UUID
	KeyID      string
	SecretEnc  []byte
	EnrolledAt *time.Time
	LastStep   int64
	At         time.Time
}

func (q *Queries) UpsertUserMFA(ctx context.Context, arg UpsertUserMFAParams) error {
	_, err := q.db.Exec(ctx, upsertUserMFA,
		arg.UserID,
		arg.KeyID,
		arg.SecretEnc,
		arg.EnrolledAt,
		arg.LastStep,
		arg.At,
	)
	return err
}

const useChallenge = `-- name: UseChallenge :exec
UPDATE login_challenges SET used_at = $1 WHERE token_hash = $2
`

type UseChallengeParams struct {
	At        *time.Time
	TokenHash string
}

func (q *Queries) UseChallenge(ctx context.Context, arg UseChallengeParams) error {
	_, err := q.db.Exec(ctx, useChallenge, arg.At, arg.TokenHash)
	return err
}

const userByID = `-- name: UserByID :one
SELECT id, username, password_hash, role, status, oidc_subject, created_at, created_by, updated_at, updated_by, last_login_at FROM users WHERE id = $1
`

func (q *Queries) UserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.LastLoginAt,
	)
	return i, err
}

const userByUsername = `-- name: UserByUsername :one

SELECT id, username, password_hash, role, status, oidc_subject, created_at, created_by, updated_at, updated_by, last_login_at FROM users WHERE username = $1
`

// WP-2: console accounts, MFA, sign-in challenges, lockouts, sessions
// and the machine clients seen (migration 0020). Every instant a query
// compares or writes is passed in from DBNow or read from
// clock_timestamp() here: the database clock, never a process clock.
func (q *Queries) UserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, userByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.LastLoginAt,
	)
	return i, err
}

const userForUpdate = `-- name: UserForUpdate :one
SELECT id, username, password_hash, role, status, oidc_subject, created_at, created_by, updated_at, updated_by, last_login_at FROM users WHERE id = $1 FOR UPDATE
`

// Locks the account row to the end of the transaction.
func (q *Queries) UserForUpdate(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, userForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.LastLoginAt,
	)
	return i, err
}

const userMFAForUpdate = `-- name: UserMFAForUpdate :one
SELECT user_id, key_id, secret_enc, enrolled_at, last_step, updated_at FROM user_mfa WHERE user_id = $1 FOR UPDATE
`

// Locks the MFA row: two sign-ins with one code race to one winner.
func (q *Queries) UserMFAForUpdate(ctx context.Context, userID uuid.UUID) (UserMfa, error) {
	row := q.db.QueryRow(ctx, userMFAForUpdate, userID)
	var i UserMfa
	err := row.Scan(
		&i.UserID,
		&i.KeyID,
		&i.SecretEnc,
		&i.EnrolledAt,
		&i.LastStep,
		&i.UpdatedAt,
	)
	return i, err
}
