// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cis.sql

package relational

import (
	"context"
	"encoding/json"
	"time"
)

const listCISVersions = `-- name: ListCISVersions :many
SELECT dataset, version, etag, fetched_at, body FROM cis_cache ORDER BY dataset LIMIT 10
`

type ListCISVersionsRow struct {
	Dataset   string
	Version   int64
	Etag      string
	FetchedAt time.Time
	Body      json.RawMessage
}

func (q *Queries) ListCISVersions(ctx context.Context) ([]ListCISVersionsRow, error) {
	rows, err := q.db.Query(ctx, listCISVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCISVersionsRow{}
	for rows.Next() {
		var i ListCISVersionsRow
		if err := rows.Scan(
			&i.Dataset,
			&i.Version,
			&i.Etag,
			&i.FetchedAt,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveCISVersion = `-- name: SaveCISVersion :one

INSERT INTO cis_cache (dataset, version, etag, fetched_at, installed_at, cis_updated_at, body)
VALUES ($1, $2, $3, clock_timestamp(), clock_timestamp(),
        $4, $5)
ON CONFLICT (dataset) DO UPDATE SET
    version = EXCLUDED.version, etag = EXCLUDED.etag, fetched_at = EXCLUDED.fetched_at,
    installed_at = CASE WHEN cis_cache.version = EXCLUDED.version THEN cis_cache.installed_at ELSE EXCLUDED.installed_at END,
    cis_updated_at = EXCLUDED.cis_updated_at, body = EXCLUDED.body
WHERE cis_cache.version <= EXCLUDED.version
RETURNING fetched_at
`

type SaveCISVersionParams struct {
	Dataset      string
	Version      int64
	Etag         string
	CisUpdatedAt *time.Time
	Body         json.RawMessage
}

// WP-7: cis_cache, the CIS projection. Every instant is the database
// clock.
// The dataset's row becomes this version unless it holds a higher one
// (the WHERE runs under the row's lock); no row back means it does.
func (q *Queries) SaveCISVersion(ctx context.Context, arg SaveCISVersionParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, saveCISVersion,
		arg.Dataset,
		arg.Version,
		arg.Etag,
		arg.CisUpdatedAt,
		arg.Body,
	)
	var fetched_at time.Time
	err := row.Scan(&fetched_at)
	return fetched_at, err
}

const touchCISVersion = `-- name: TouchCISVersion :one
UPDATE cis_cache SET fetched_at = clock_timestamp()
WHERE dataset = $1 AND version = $2
RETURNING fetched_at
`

type TouchCISVersionParams struct {
	Dataset string
	Version int64
}

// The CISP confirmed the version (304): fetched_at moves.
func (q *Queries) TouchCISVersion(ctx context.Context, arg TouchCISVersionParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, touchCISVersion, arg.Dataset, arg.Version)
	var fetched_at time.Time
	err := row.Scan(&fetched_at)
	return fetched_at, err
}
