// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cis.sql

package relational

import (
	"context"
	"encoding/json"
	"time"
)

const cISNotificationLive = `-- name: CISNotificationLive :one
SELECT
    EXISTS (SELECT 1 FROM cis_notifications_seen s
            WHERE s.issuer = $1 AND s.jti = $2 AND s.expires_at > clock_timestamp()) AS seen,
    (SELECT count(*) FROM cis_notifications_seen l WHERE l.expires_at > clock_timestamp())::bigint AS live
`

type CISNotificationLiveParams struct {
	Issuer string
	Jti    string
}

type CISNotificationLiveRow struct {
	Seen bool
	Live int64
}

// Whether the delivery id is remembered and not expired, and how many
// delivery ids are.
func (q *Queries) CISNotificationLive(ctx context.Context, arg CISNotificationLiveParams) (CISNotificationLiveRow, error) {
	row := q.db.QueryRow(ctx, cISNotificationLive, arg.Issuer, arg.Jti)
	var i CISNotificationLiveRow
	err := row.Scan(&i.Seen, &i.Live)
	return i, err
}

const listCISVersions = `-- name: ListCISVersions :many
SELECT dataset, version, etag, fetched_at, body FROM cis_cache ORDER BY dataset LIMIT 10
`

type ListCISVersionsRow struct {
	Dataset   string
	Version   int64
	Etag      string
	FetchedAt time.Time
	Body      json.RawMessage
}

func (q *Queries) ListCISVersions(ctx context.Context) ([]ListCISVersionsRow, error) {
	rows, err := q.db.Query(ctx, listCISVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCISVersionsRow{}
	for rows.Next() {
		var i ListCISVersionsRow
		if err := rows.Scan(
			&i.Dataset,
			&i.Version,
			&i.Etag,
			&i.FetchedAt,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rememberCISNotification = `-- name: RememberCISNotification :one
INSERT INTO cis_notifications_seen (issuer, jti, seen_at, expires_at)
VALUES ($1, $2, clock_timestamp(), clock_timestamp() + make_interval(secs => $3::float8))
ON CONFLICT (issuer, jti) DO UPDATE SET seen_at = EXCLUDED.seen_at, expires_at = EXCLUDED.expires_at
WHERE cis_notifications_seen.expires_at <= clock_timestamp()
RETURNING expires_at
`

type RememberCISNotificationParams struct {
	Issuer string
	Jti    string
	TtlS   float64
}

// Records the delivery id for ttl_s; an expired row of the same id is
// reused. No row back means the id is live: a replay, or a concurrent
// delivery of the same id that won.
func (q *Queries) RememberCISNotification(ctx context.Context, arg RememberCISNotificationParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, rememberCISNotification, arg.Issuer, arg.Jti, arg.TtlS)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const saveCISVersion = `-- name: SaveCISVersion :one

INSERT INTO cis_cache (dataset, version, etag, fetched_at, installed_at, cis_updated_at, body)
VALUES ($1, $2, $3, clock_timestamp(), clock_timestamp(),
        $4, $5)
ON CONFLICT (dataset) DO UPDATE SET
    version = EXCLUDED.version, etag = EXCLUDED.etag, fetched_at = EXCLUDED.fetched_at,
    installed_at = CASE WHEN cis_cache.version = EXCLUDED.version THEN cis_cache.installed_at ELSE EXCLUDED.installed_at END,
    cis_updated_at = EXCLUDED.cis_updated_at, body = EXCLUDED.body
WHERE cis_cache.version <= EXCLUDED.version
RETURNING fetched_at
`

type SaveCISVersionParams struct {
	Dataset      string
	Version      int64
	Etag         string
	CisUpdatedAt *time.Time
	Body         json.RawMessage
}

// WP-7: cis_cache, the CIS projection, and cis_notifications_seen, the
// replay guard of the CISP's change notifications. Every instant is the
// database clock.
// The dataset's row becomes this version unless it holds a higher one
// (the WHERE runs under the row's lock); no row back means it does.
func (q *Queries) SaveCISVersion(ctx context.Context, arg SaveCISVersionParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, saveCISVersion,
		arg.Dataset,
		arg.Version,
		arg.Etag,
		arg.CisUpdatedAt,
		arg.Body,
	)
	var fetched_at time.Time
	err := row.Scan(&fetched_at)
	return fetched_at, err
}

const sweepCISNotifications = `-- name: SweepCISNotifications :execrows
DELETE FROM cis_notifications_seen
WHERE ctid IN (SELECT ctid FROM cis_notifications_seen WHERE expires_at <= clock_timestamp() LIMIT $1)
`

// Deletes at most max_rows expired delivery ids.
func (q *Queries) SweepCISNotifications(ctx context.Context, maxRows int32) (int64, error) {
	result, err := q.db.Exec(ctx, sweepCISNotifications, maxRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchCISVersion = `-- name: TouchCISVersion :one
UPDATE cis_cache SET fetched_at = clock_timestamp()
WHERE dataset = $1 AND version = $2
RETURNING fetched_at
`

type TouchCISVersionParams struct {
	Dataset string
	Version int64
}

// The CISP confirmed the version (304): fetched_at moves.
func (q *Queries) TouchCISVersion(ctx context.Context, arg TouchCISVersionParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, touchCISVersion, arg.Dataset, arg.Version)
	var fetched_at time.Time
	err := row.Scan(&fetched_at)
	return fetched_at, err
}
