// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coord.sql

package relational

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const acknowledgeNotice = `-- name: AcknowledgeNotice :one
UPDATE coordination_notices SET
    state = 'acknowledged', acknowledged_by = $1, acknowledged_user = $2,
    acknowledged_at = clock_timestamp(), ack_note = $3, event_seq = event_seq + 1
WHERE id = $4 AND state = 'received'
RETURNING id, kind, sender_client_id, ussp_id, notice_ref, payload, payload_sha256, intent_refs, authorisation_numbers, received_at, state, ack_required, sender_unverified, acknowledged_by, acknowledged_user, acknowledged_at, ack_note, escalated_at, last_escalated_at, escalations, restriction_ids, cis_version, event_seq, bus_seq
`

type AcknowledgeNoticeParams struct {
	Role   *string
	UserID *string
	Note   *string
	ID     string
}

// A person's acknowledgement (Art. 13(2)); no row back when the notice
// is acknowledged already or does not exist.
func (q *Queries) AcknowledgeNotice(ctx context.Context, arg AcknowledgeNoticeParams) (CoordinationNotice, error) {
	row := q.db.QueryRow(ctx, acknowledgeNotice,
		arg.Role,
		arg.UserID,
		arg.Note,
		arg.ID,
	)
	var i CoordinationNotice
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SenderClientID,
		&i.UsspID,
		&i.NoticeRef,
		&i.Payload,
		&i.PayloadSha256,
		&i.IntentRefs,
		&i.AuthorisationNumbers,
		&i.ReceivedAt,
		&i.State,
		&i.AckRequired,
		&i.SenderUnverified,
		&i.AcknowledgedBy,
		&i.AcknowledgedUser,
		&i.AcknowledgedAt,
		&i.AckNote,
		&i.EscalatedAt,
		&i.LastEscalatedAt,
		&i.Escalations,
		&i.RestrictionIds,
		&i.CisVersion,
		&i.EventSeq,
		&i.BusSeq,
	)
	return i, err
}

const countNoticesBehindBus = `-- name: CountNoticesBehindBus :one
SELECT count(*)::bigint FROM coordination_notices WHERE bus_seq < event_seq
`

func (q *Queries) CountNoticesBehindBus(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNoticesBehindBus)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSenderNotices = `-- name: CountSenderNotices :one
SELECT count(*) FROM coordination_notices
WHERE sender_client_id = $1
  AND (received_at >= $2::timestamptz OR (state = 'received' AND ack_required))
`

type CountSenderNoticesParams struct {
	SenderClientID string
	Since          time.Time
}

// The sender's notices received since, or still awaiting a person's
// acknowledgement (the per-sender quota, ansp audit S-9).
func (q *Queries) CountSenderNotices(ctx context.Context, arg CountSenderNoticesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSenderNotices, arg.SenderClientID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deliveredOccurrenceAlarms = `-- name: DeliveredOccurrenceAlarms :many
SELECT a.id, a.delivery_id
FROM delivery_alarms a JOIN deliveries d ON d.id = a.delivery_id
WHERE a.kind = 'occurrence_undelivered' AND a.cleared_at IS NULL AND d.state = 'sent'
ORDER BY a.raised_at
LIMIT $1
`

type DeliveredOccurrenceAlarmsRow struct {
	ID         string
	DeliveryID *string
}

// Open occurrence_undelivered alarms whose report is now delivered.
func (q *Queries) DeliveredOccurrenceAlarms(ctx context.Context, pageSize int32) ([]DeliveredOccurrenceAlarmsRow, error) {
	rows, err := q.db.Query(ctx, deliveredOccurrenceAlarms, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveredOccurrenceAlarmsRow{}
	for rows.Next() {
		var i DeliveredOccurrenceAlarmsRow
		if err := rows.Scan(&i.ID, &i.DeliveryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const escalateDue = `-- name: EscalateDue :many
UPDATE coordination_notices n SET
    escalated_at = COALESCE(n.escalated_at, $1::timestamptz), last_escalated_at = $1::timestamptz,
    escalations = n.escalations + 1, event_seq = n.event_seq + 1
WHERE n.id IN (
    SELECT c.id FROM coordination_notices c
    WHERE c.state = 'received' AND c.ack_required
      AND c.received_at <= $1::timestamptz - make_interval(secs => $2::float8)
      AND (c.last_escalated_at IS NULL
           OR c.last_escalated_at <= $1::timestamptz - make_interval(secs => $3::float8))
    ORDER BY c.received_at
    LIMIT $4
    FOR UPDATE SKIP LOCKED)
RETURNING n.id, n.kind, n.sender_client_id, n.ussp_id, n.notice_ref, n.payload, n.payload_sha256, n.intent_refs, n.authorisation_numbers, n.received_at, n.state, n.ack_required, n.sender_unverified, n.acknowledged_by, n.acknowledged_user, n.acknowledged_at, n.ack_note, n.escalated_at, n.last_escalated_at, n.escalations, n.restriction_ids, n.cis_version, n.event_seq, n.bus_seq
`

type EscalateDueParams struct {
	Now         time.Time
	EscalationS float64
	RepeatS     float64
	PageSize    int32
}

// The notices that need a person and have none: not acknowledged
// escalation_s after receipt, then again every repeat_s. Rows another
// replica is escalating are skipped, so each escalation happens once.
func (q *Queries) EscalateDue(ctx context.Context, arg EscalateDueParams) ([]CoordinationNotice, error) {
	rows, err := q.db.Query(ctx, escalateDue,
		arg.Now,
		arg.EscalationS,
		arg.RepeatS,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoordinationNotice{}
	for rows.Next() {
		var i CoordinationNotice
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.SenderClientID,
			&i.UsspID,
			&i.NoticeRef,
			&i.Payload,
			&i.PayloadSha256,
			&i.IntentRefs,
			&i.AuthorisationNumbers,
			&i.ReceivedAt,
			&i.State,
			&i.AckRequired,
			&i.SenderUnverified,
			&i.AcknowledgedBy,
			&i.AcknowledgedUser,
			&i.AcknowledgedAt,
			&i.AckNote,
			&i.EscalatedAt,
			&i.LastEscalatedAt,
			&i.Escalations,
			&i.RestrictionIds,
			&i.CisVersion,
			&i.EventSeq,
			&i.BusSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNotice = `-- name: InsertNotice :one

INSERT INTO coordination_notices (id, kind, sender_client_id, ussp_id, notice_ref, payload, payload_sha256, intent_refs,
                                  authorisation_numbers, ack_required, sender_unverified, restriction_ids, cis_version, received_at)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8::uuid[], $9::text[], $10,
        $11, $12::text[], $13, $14)
ON CONFLICT ON CONSTRAINT coordination_notices_sender_ref DO NOTHING
RETURNING id, kind, sender_client_id, ussp_id, notice_ref, payload, payload_sha256, intent_refs, authorisation_numbers, received_at, state, ack_required, sender_unverified, acknowledged_by, acknowledged_user, acknowledged_at, ack_note, escalated_at, last_escalated_at, escalations, restriction_ids, cis_version, event_seq, bus_seq
`

type InsertNoticeParams struct {
	ID                   string
	Kind                 string
	SenderClientID       string
	UsspID               string
	NoticeRef            string
	Payload              json.RawMessage
	PayloadSha256        []byte
	IntentRefs           []uuid.UUID
	AuthorisationNumbers []string
	AckRequired          bool
	SenderUnverified     bool
	RestrictionIds       []string
	CisVersion           *string
	ReceivedAt           time.Time
}

// WP-10: the Annex V inbox and the occurrence reports (internal/coord).
// Every instant is the database clock, or the clock the service passes
// as now (its default is the database clock; a test passes a fake one).
// A received notice; no row back means the sender sent this notice_ref
// before (the caller reads that one).
func (q *Queries) InsertNotice(ctx context.Context, arg InsertNoticeParams) (CoordinationNotice, error) {
	row := q.db.QueryRow(ctx, insertNotice,
		arg.ID,
		arg.Kind,
		arg.SenderClientID,
		arg.UsspID,
		arg.NoticeRef,
		arg.Payload,
		arg.PayloadSha256,
		arg.IntentRefs,
		arg.AuthorisationNumbers,
		arg.AckRequired,
		arg.SenderUnverified,
		arg.RestrictionIds,
		arg.CisVersion,
		arg.ReceivedAt,
	)
	var i CoordinationNotice
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SenderClientID,
		&i.UsspID,
		&i.NoticeRef,
		&i.Payload,
		&i.PayloadSha256,
		&i.IntentRefs,
		&i.AuthorisationNumbers,
		&i.ReceivedAt,
		&i.State,
		&i.AckRequired,
		&i.SenderUnverified,
		&i.AcknowledgedBy,
		&i.AcknowledgedUser,
		&i.AcknowledgedAt,
		&i.AckNote,
		&i.EscalatedAt,
		&i.LastEscalatedAt,
		&i.Escalations,
		&i.RestrictionIds,
		&i.CisVersion,
		&i.EventSeq,
		&i.BusSeq,
	)
	return i, err
}

const insertOccurrence = `-- name: InsertOccurrence :one
INSERT INTO occurrence_reports (id, report_ref, channel, occurred_at, became_aware_at, category, aircraft, manned, intent_refs,
                                min_separation, narrative, reporter_person_ref_sealed, reporter_key_id, created_by, delivery_id,
                                deadline_at)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9::uuid[], $10, $11,
        $12, $13, $14, $15,
        $5::timestamptz + interval '72 hours')
RETURNING id, report_ref, channel, occurred_at, became_aware_at, category, aircraft, manned, intent_refs, min_separation, narrative, reporter_person_ref_sealed, reporter_key_id, created_by, created_at, delivery_id, deadline_at
`

type InsertOccurrenceParams struct {
	ID                      string
	ReportRef               string
	Channel                 string
	OccurredAt              time.Time
	BecameAwareAt           time.Time
	Category                string
	Aircraft                json.RawMessage
	Manned                  json.RawMessage
	IntentRefs              []uuid.UUID
	MinSeparation           json.RawMessage
	Narrative               string
	ReporterPersonRefSealed []byte
	ReporterKeyID           *string
	CreatedBy               string
	DeliveryID              string
}

func (q *Queries) InsertOccurrence(ctx context.Context, arg InsertOccurrenceParams) (OccurrenceReport, error) {
	row := q.db.QueryRow(ctx, insertOccurrence,
		arg.ID,
		arg.ReportRef,
		arg.Channel,
		arg.OccurredAt,
		arg.BecameAwareAt,
		arg.Category,
		arg.Aircraft,
		arg.Manned,
		arg.IntentRefs,
		arg.MinSeparation,
		arg.Narrative,
		arg.ReporterPersonRefSealed,
		arg.ReporterKeyID,
		arg.CreatedBy,
		arg.DeliveryID,
	)
	var i OccurrenceReport
	err := row.Scan(
		&i.ID,
		&i.ReportRef,
		&i.Channel,
		&i.OccurredAt,
		&i.BecameAwareAt,
		&i.Category,
		&i.Aircraft,
		&i.Manned,
		&i.IntentRefs,
		&i.MinSeparation,
		&i.Narrative,
		&i.ReporterPersonRefSealed,
		&i.ReporterKeyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeliveryID,
		&i.DeadlineAt,
	)
	return i, err
}

const intersectingRestrictions = `-- name: IntersectingRestrictions :many
SELECT DISTINCT r.id
FROM restrictions r,
     jsonb_to_recordset($1::jsonb)
         AS b(min_lon double precision, min_lat double precision, max_lon double precision, max_lat double precision,
              t_start timestamptz, t_end timestamptz)
WHERE r.state IN ('planned', 'active')
  AND r.starts_at < b.t_end AND r.ends_at > b.t_start
  AND ST_Intersects(
        CASE WHEN r.radius_m IS NULL THEN r.geom ELSE ST_Buffer(r.geom::geography, r.radius_m)::geometry END,
        ST_MakeEnvelope(b.min_lon, b.min_lat, b.max_lon, b.max_lat, 4326))
ORDER BY r.id
LIMIT $2
`

type IntersectingRestrictionsParams struct {
	Boxes    json.RawMessage
	PageSize int32
}

// The planned or active restrictions that intersect any of the boxes
// (each the conservative envelope of one notice volume, uspace-core
// f3548.Volume4DToZonesEnvelope, as a JSON array of {min_lon, min_lat,
// max_lon, max_lat, t_start, t_end}) in its time window: a polygon in
// degrees against the box, a circle as its geodesic buffer.
func (q *Queries) IntersectingRestrictions(ctx context.Context, arg IntersectingRestrictionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, intersectingRestrictions, arg.Boxes, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotices = `-- name: ListNotices :many
SELECT id, kind, sender_client_id, ussp_id, notice_ref, payload, payload_sha256, intent_refs, authorisation_numbers, received_at, state, ack_required, sender_unverified, acknowledged_by, acknowledged_user, acknowledged_at, ack_note, escalated_at, last_escalated_at, escalations, restriction_ids, cis_version, event_seq, bus_seq FROM coordination_notices
WHERE ($1::text IS NULL
       OR ($1::text = 'received' AND state = 'received' AND escalated_at IS NULL)
       OR ($1::text = 'escalated' AND state = 'received' AND escalated_at IS NOT NULL)
       OR ($1::text = 'open' AND state = 'received')
       OR ($1::text = 'acknowledged' AND state = 'acknowledged'))
  AND ($2::timestamptz IS NULL OR received_at >= $2::timestamptz)
ORDER BY received_at DESC, id DESC
LIMIT $3
`

type ListNoticesParams struct {
	State    *string
	Since    *time.Time
	PageSize int32
}

// The inbox, newest first: state received (not escalated), escalated
// (received and escalated) or acknowledged; open is every notice not
// acknowledged (the console's snapshot).
func (q *Queries) ListNotices(ctx context.Context, arg ListNoticesParams) ([]CoordinationNotice, error) {
	rows, err := q.db.Query(ctx, listNotices, arg.State, arg.Since, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoordinationNotice{}
	for rows.Next() {
		var i CoordinationNotice
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.SenderClientID,
			&i.UsspID,
			&i.NoticeRef,
			&i.Payload,
			&i.PayloadSha256,
			&i.IntentRefs,
			&i.AuthorisationNumbers,
			&i.ReceivedAt,
			&i.State,
			&i.AckRequired,
			&i.SenderUnverified,
			&i.AcknowledgedBy,
			&i.AcknowledgedUser,
			&i.AcknowledgedAt,
			&i.AckNote,
			&i.EscalatedAt,
			&i.LastEscalatedAt,
			&i.Escalations,
			&i.RestrictionIds,
			&i.CisVersion,
			&i.EventSeq,
			&i.BusSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNoticeBus = `-- name: MarkNoticeBus :exec
UPDATE coordination_notices SET bus_seq = GREATEST(bus_seq, $1::int)
WHERE id = $2 AND $1::int <= event_seq
`

type MarkNoticeBusParams struct {
	Seq int32
	ID  string
}

func (q *Queries) MarkNoticeBus(ctx context.Context, arg MarkNoticeBusParams) error {
	_, err := q.db.Exec(ctx, markNoticeBus, arg.Seq, arg.ID)
	return err
}

const nextOccurrenceRef = `-- name: NextOccurrenceRef :one
SELECT ('ANSP-OCC-' || to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY') || '-'
        || lpad(nextval('occurrence_report_seq')::text, 4, '0'))::text AS report_ref
`

func (q *Queries) NextOccurrenceRef(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, nextOccurrenceRef)
	var report_ref string
	err := row.Scan(&report_ref)
	return report_ref, err
}

const noticeByID = `-- name: NoticeByID :one
SELECT id, kind, sender_client_id, ussp_id, notice_ref, payload, payload_sha256, intent_refs, authorisation_numbers, received_at, state, ack_required, sender_unverified, acknowledged_by, acknowledged_user, acknowledged_at, ack_note, escalated_at, last_escalated_at, escalations, restriction_ids, cis_version, event_seq, bus_seq FROM coordination_notices WHERE id = $1
`

func (q *Queries) NoticeByID(ctx context.Context, id string) (CoordinationNotice, error) {
	row := q.db.QueryRow(ctx, noticeByID, id)
	var i CoordinationNotice
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SenderClientID,
		&i.UsspID,
		&i.NoticeRef,
		&i.Payload,
		&i.PayloadSha256,
		&i.IntentRefs,
		&i.AuthorisationNumbers,
		&i.ReceivedAt,
		&i.State,
		&i.AckRequired,
		&i.SenderUnverified,
		&i.AcknowledgedBy,
		&i.AcknowledgedUser,
		&i.AcknowledgedAt,
		&i.AckNote,
		&i.EscalatedAt,
		&i.LastEscalatedAt,
		&i.Escalations,
		&i.RestrictionIds,
		&i.CisVersion,
		&i.EventSeq,
		&i.BusSeq,
	)
	return i, err
}

const noticeBySenderRef = `-- name: NoticeBySenderRef :one
SELECT id, kind, sender_client_id, ussp_id, notice_ref, payload, payload_sha256, intent_refs, authorisation_numbers, received_at, state, ack_required, sender_unverified, acknowledged_by, acknowledged_user, acknowledged_at, ack_note, escalated_at, last_escalated_at, escalations, restriction_ids, cis_version, event_seq, bus_seq FROM coordination_notices WHERE sender_client_id = $1 AND notice_ref = $2
`

type NoticeBySenderRefParams struct {
	SenderClientID string
	NoticeRef      string
}

func (q *Queries) NoticeBySenderRef(ctx context.Context, arg NoticeBySenderRefParams) (CoordinationNotice, error) {
	row := q.db.QueryRow(ctx, noticeBySenderRef, arg.SenderClientID, arg.NoticeRef)
	var i CoordinationNotice
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SenderClientID,
		&i.UsspID,
		&i.NoticeRef,
		&i.Payload,
		&i.PayloadSha256,
		&i.IntentRefs,
		&i.AuthorisationNumbers,
		&i.ReceivedAt,
		&i.State,
		&i.AckRequired,
		&i.SenderUnverified,
		&i.AcknowledgedBy,
		&i.AcknowledgedUser,
		&i.AcknowledgedAt,
		&i.AckNote,
		&i.EscalatedAt,
		&i.LastEscalatedAt,
		&i.Escalations,
		&i.RestrictionIds,
		&i.CisVersion,
		&i.EventSeq,
		&i.BusSeq,
	)
	return i, err
}

const noticesBehindBus = `-- name: NoticesBehindBus :many
SELECT id, kind, sender_client_id, ussp_id, notice_ref, payload, payload_sha256, intent_refs, authorisation_numbers, received_at, state, ack_required, sender_unverified, acknowledged_by, acknowledged_user, acknowledged_at, ack_note, escalated_at, last_escalated_at, escalations, restriction_ids, cis_version, event_seq, bus_seq FROM coordination_notices WHERE bus_seq < event_seq ORDER BY id LIMIT $1
`

// Notices whose latest change is not on coord.v1 yet.
func (q *Queries) NoticesBehindBus(ctx context.Context, pageSize int32) ([]CoordinationNotice, error) {
	rows, err := q.db.Query(ctx, noticesBehindBus, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoordinationNotice{}
	for rows.Next() {
		var i CoordinationNotice
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.SenderClientID,
			&i.UsspID,
			&i.NoticeRef,
			&i.Payload,
			&i.PayloadSha256,
			&i.IntentRefs,
			&i.AuthorisationNumbers,
			&i.ReceivedAt,
			&i.State,
			&i.AckRequired,
			&i.SenderUnverified,
			&i.AcknowledgedBy,
			&i.AcknowledgedUser,
			&i.AcknowledgedAt,
			&i.AckNote,
			&i.EscalatedAt,
			&i.LastEscalatedAt,
			&i.Escalations,
			&i.RestrictionIds,
			&i.CisVersion,
			&i.EventSeq,
			&i.BusSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const occurrenceByDelivery = `-- name: OccurrenceByDelivery :one
SELECT id, report_ref, channel, occurred_at, became_aware_at, category, aircraft, manned, intent_refs, min_separation, narrative, reporter_person_ref_sealed, reporter_key_id, created_by, created_at, delivery_id, deadline_at FROM occurrence_reports WHERE delivery_id = $1
`

func (q *Queries) OccurrenceByDelivery(ctx context.Context, deliveryID string) (OccurrenceReport, error) {
	row := q.db.QueryRow(ctx, occurrenceByDelivery, deliveryID)
	var i OccurrenceReport
	err := row.Scan(
		&i.ID,
		&i.ReportRef,
		&i.Channel,
		&i.OccurredAt,
		&i.BecameAwareAt,
		&i.Category,
		&i.Aircraft,
		&i.Manned,
		&i.IntentRefs,
		&i.MinSeparation,
		&i.Narrative,
		&i.ReporterPersonRefSealed,
		&i.ReporterKeyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeliveryID,
		&i.DeadlineAt,
	)
	return i, err
}

const undeliveredOccurrences = `-- name: UndeliveredOccurrences :many
SELECT o.id, o.report_ref, o.delivery_id, o.became_aware_at, o.deadline_at, d.state AS delivery_state
FROM occurrence_reports o JOIN deliveries d ON d.id = o.delivery_id
WHERE d.state <> 'sent'
  AND o.became_aware_at <= $1::timestamptz - make_interval(secs => $2::float8)
  AND NOT EXISTS (SELECT 1 FROM delivery_alarms a WHERE a.delivery_id = o.delivery_id AND a.kind = 'occurrence_undelivered')
ORDER BY o.became_aware_at
LIMIT $3
`

type UndeliveredOccurrencesParams struct {
	Now         time.Time
	AlarmAfterS float64
	PageSize    int32
}

type UndeliveredOccurrencesRow struct {
	ID            string
	ReportRef     string
	DeliveryID    string
	BecameAwareAt time.Time
	DeadlineAt    time.Time
	DeliveryState DeliveryState
}

// Reports whose delivery is not sent alarm_after_s after became_aware_at
// (at now) and have no occurrence_undelivered alarm yet.
func (q *Queries) UndeliveredOccurrences(ctx context.Context, arg UndeliveredOccurrencesParams) ([]UndeliveredOccurrencesRow, error) {
	rows, err := q.db.Query(ctx, undeliveredOccurrences, arg.Now, arg.AlarmAfterS, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UndeliveredOccurrencesRow{}
	for rows.Next() {
		var i UndeliveredOccurrencesRow
		if err := rows.Scan(
			&i.ID,
			&i.ReportRef,
			&i.DeliveryID,
			&i.BecameAwareAt,
			&i.DeadlineAt,
			&i.DeliveryState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
