// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package relational

import (
	"context"
	"time"
)

const acknowledgeAlarm = `-- name: AcknowledgeAlarm :one
UPDATE delivery_alarms SET
    acknowledged_by = $1, acknowledged_at = clock_timestamp(), ack_reason = $2,
    cleared_at = CASE WHEN kind IN ('cisp_not_published', 'uss_notify_late') THEN cleared_at ELSE clock_timestamp() END,
    clear_reason = CASE WHEN kind IN ('cisp_not_published', 'uss_notify_late') THEN clear_reason ELSE 'acknowledged' END
WHERE id = $3 AND acknowledged_at IS NULL AND cleared_at IS NULL
RETURNING id, kind, restriction_id, ansp_version, delivery_id, raised_at, since, detail, cleared_at, clear_reason, acknowledged_by, acknowledged_at, ack_reason
`

type AcknowledgeAlarmParams struct {
	By     *string
	Reason *string
	ID     string
}

// A person's acknowledgement: it closes a failed or abandoned delivery's
// alarm; a cisp_not_published or uss_notify_late alarm stays open until
// what resolves it.
func (q *Queries) AcknowledgeAlarm(ctx context.Context, arg AcknowledgeAlarmParams) (DeliveryAlarm, error) {
	row := q.db.QueryRow(ctx, acknowledgeAlarm, arg.By, arg.Reason, arg.ID)
	var i DeliveryAlarm
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RestrictionID,
		&i.AnspVersion,
		&i.DeliveryID,
		&i.RaisedAt,
		&i.Since,
		&i.Detail,
		&i.ClearedAt,
		&i.ClearReason,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.AckReason,
	)
	return i, err
}

const activeAnspRefs = `-- name: ActiveAnspRefs :many
SELECT ansp_ref FROM restrictions WHERE state = 'active' ORDER BY ansp_ref LIMIT $1
`

func (q *Queries) ActiveAnspRefs(ctx context.Context, pageSize int32) ([]string, error) {
	rows, err := q.db.Query(ctx, activeAnspRefs, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var ansp_ref string
		if err := rows.Scan(&ansp_ref); err != nil {
			return nil, err
		}
		items = append(items, ansp_ref)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const advanceAlarm = `-- name: AdvanceAlarm :exec
UPDATE delivery_alarms SET ansp_version = $1, detail = $2
WHERE id = $3 AND cleared_at IS NULL AND ansp_version < $1
`

type AdvanceAlarmParams struct {
	AnspVersion *int64
	Detail      string
	ID          string
}

func (q *Queries) AdvanceAlarm(ctx context.Context, arg AdvanceAlarmParams) error {
	_, err := q.db.Exec(ctx, advanceAlarm, arg.AnspVersion, arg.Detail, arg.ID)
	return err
}

const alarmByID = `-- name: AlarmByID :one
SELECT id, kind, restriction_id, ansp_version, delivery_id, raised_at, since, detail, cleared_at, clear_reason, acknowledged_by, acknowledged_at, ack_reason FROM delivery_alarms WHERE id = $1
`

func (q *Queries) AlarmByID(ctx context.Context, id string) (DeliveryAlarm, error) {
	row := q.db.QueryRow(ctx, alarmByID, id)
	var i DeliveryAlarm
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RestrictionID,
		&i.AnspVersion,
		&i.DeliveryID,
		&i.RaisedAt,
		&i.Since,
		&i.Detail,
		&i.ClearedAt,
		&i.ClearReason,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.AckReason,
	)
	return i, err
}

const alarmOfDelivery = `-- name: AlarmOfDelivery :one
SELECT id, kind, restriction_id, ansp_version, delivery_id, raised_at, since, detail, cleared_at, clear_reason, acknowledged_by, acknowledged_at, ack_reason FROM delivery_alarms WHERE delivery_id = $1 AND kind = $2
`

type AlarmOfDeliveryParams struct {
	DeliveryID *string
	Kind       string
}

func (q *Queries) AlarmOfDelivery(ctx context.Context, arg AlarmOfDeliveryParams) (DeliveryAlarm, error) {
	row := q.db.QueryRow(ctx, alarmOfDelivery, arg.DeliveryID, arg.Kind)
	var i DeliveryAlarm
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RestrictionID,
		&i.AnspVersion,
		&i.DeliveryID,
		&i.RaisedAt,
		&i.Since,
		&i.Detail,
		&i.ClearedAt,
		&i.ClearReason,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.AckReason,
	)
	return i, err
}

const cancelQueuedDeliveries = `-- name: CancelQueuedDeliveries :many
UPDATE deliveries SET state = 'cancelled', cancel_reason = $1, lease_token = NULL, lease_until = NULL
WHERE kind = $2 AND restriction_id = $3 AND ansp_version <= $4
  AND state = 'queued'
RETURNING id, target, ansp_version
`

type CancelQueuedDeliveriesParams struct {
	Reason        *string
	Kind          DeliveryKind
	RestrictionID *string
	UpTo          *int64
}

type CancelQueuedDeliveriesRow struct {
	ID          string
	Target      string
	AnspVersion *int64
}

func (q *Queries) CancelQueuedDeliveries(ctx context.Context, arg CancelQueuedDeliveriesParams) ([]CancelQueuedDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, cancelQueuedDeliveries,
		arg.Reason,
		arg.Kind,
		arg.RestrictionID,
		arg.UpTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CancelQueuedDeliveriesRow{}
	for rows.Next() {
		var i CancelQueuedDeliveriesRow
		if err := rows.Scan(&i.ID, &i.Target, &i.AnspVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimDelivery = `-- name: ClaimDelivery :one
UPDATE deliveries d SET
    lease_token = $1, lease_until = clock_timestamp() + make_interval(secs => $2::float8),
    attempt = d.attempt + 1, last_attempt_at = clock_timestamp()
WHERE d.id = $3 AND d.state = 'queued'
  AND (d.lease_until IS NULL OR d.lease_until < clock_timestamp())
  AND d.next_retry_at <= clock_timestamp()
  AND NOT EXISTS (
      SELECT 1 FROM deliveries p
      WHERE (p.kind = d.kind OR (p.kind IN ('dss_put', 'dss_delete') AND d.kind IN ('dss_put', 'dss_delete')))
        AND p.restriction_id = d.restriction_id AND p.target = d.target
        AND p.ansp_version < d.ansp_version AND p.state = 'queued')
RETURNING d.id, d.kind, d.subject_ref, d.restriction_id, d.ansp_version, d.op, d.target, d.idempotency_key, d.state,
          d.attempt, d.max_attempts, d.queued_at, d.window_ends_at, d.next_retry_at, d.bus_seq, d.last_attempt_at,
          d.sent_at, d.status_code, d.response_excerpt, d.last_error, d.method, d.url, d.body, d.cancel_reason,
          clock_timestamp()::timestamptz AS now
`

type ClaimDeliveryParams struct {
	Token  *string
	LeaseS float64
	ID     string
}

type ClaimDeliveryRow struct {
	ID              string
	Kind            DeliveryKind
	SubjectRef      string
	RestrictionID   *string
	AnspVersion     *int64
	Op              string
	Target          string
	IdempotencyKey  string
	State           DeliveryState
	Attempt         int32
	MaxAttempts     int32
	QueuedAt        time.Time
	WindowEndsAt    time.Time
	NextRetryAt     time.Time
	BusSeq          int32
	LastAttemptAt   *time.Time
	SentAt          *time.Time
	StatusCode      *int32
	ResponseExcerpt *string
	LastError       *string
	Method          *string
	Url             *string
	Body            []byte
	CancelReason    *string
	Now             time.Time
}

// Leases a queued, due row whose earlier versions to the same target
// are settled, for one attempt. The DSS writes of a restriction (put and
// delete) are one channel: a delete waits for the put before it (WP-9).
func (q *Queries) ClaimDelivery(ctx context.Context, arg ClaimDeliveryParams) (ClaimDeliveryRow, error) {
	row := q.db.QueryRow(ctx, claimDelivery, arg.Token, arg.LeaseS, arg.ID)
	var i ClaimDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SubjectRef,
		&i.RestrictionID,
		&i.AnspVersion,
		&i.Op,
		&i.Target,
		&i.IdempotencyKey,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.QueuedAt,
		&i.WindowEndsAt,
		&i.NextRetryAt,
		&i.BusSeq,
		&i.LastAttemptAt,
		&i.SentAt,
		&i.StatusCode,
		&i.ResponseExcerpt,
		&i.LastError,
		&i.Method,
		&i.Url,
		&i.Body,
		&i.CancelReason,
		&i.Now,
	)
	return i, err
}

const clearCISPAlarm = `-- name: ClearCISPAlarm :one
UPDATE delivery_alarms SET cleared_at = clock_timestamp(), clear_reason = $1
WHERE restriction_id = $2 AND kind = 'cisp_not_published' AND cleared_at IS NULL
RETURNING id, kind, restriction_id, ansp_version, delivery_id, raised_at, since, detail, cleared_at, clear_reason, acknowledged_by, acknowledged_at, ack_reason
`

type ClearCISPAlarmParams struct {
	Reason        *string
	RestrictionID *string
}

func (q *Queries) ClearCISPAlarm(ctx context.Context, arg ClearCISPAlarmParams) (DeliveryAlarm, error) {
	row := q.db.QueryRow(ctx, clearCISPAlarm, arg.Reason, arg.RestrictionID)
	var i DeliveryAlarm
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RestrictionID,
		&i.AnspVersion,
		&i.DeliveryID,
		&i.RaisedAt,
		&i.Since,
		&i.Detail,
		&i.ClearedAt,
		&i.ClearReason,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.AckReason,
	)
	return i, err
}

const clearableAlarms = `-- name: ClearableAlarms :many
SELECT a.id, a.restriction_id, r.state, r.ansp_version, COALESCE(r.published_version, 0)::bigint AS published_version
FROM delivery_alarms a JOIN restrictions r ON r.id = a.restriction_id
WHERE a.kind = 'cisp_not_published' AND a.cleared_at IS NULL
  AND (r.state <> 'active' OR COALESCE(r.published_version, 0) >= r.ansp_version)
ORDER BY a.raised_at
LIMIT $1
`

type ClearableAlarmsRow struct {
	ID               string
	RestrictionID    *string
	State            RestrictionState
	AnspVersion      int64
	PublishedVersion int64
}

func (q *Queries) ClearableAlarms(ctx context.Context, pageSize int32) ([]ClearableAlarmsRow, error) {
	rows, err := q.db.Query(ctx, clearableAlarms, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClearableAlarmsRow{}
	for rows.Next() {
		var i ClearableAlarmsRow
		if err := rows.Scan(
			&i.ID,
			&i.RestrictionID,
			&i.State,
			&i.AnspVersion,
			&i.PublishedVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDeliveryAttempts = `-- name: CountDeliveryAttempts :one
SELECT count(*)::bigint FROM delivery_attempts WHERE delivery_id = $1
`

func (q *Queries) CountDeliveryAttempts(ctx context.Context, deliveryID string) (int64, error) {
	row := q.db.QueryRow(ctx, countDeliveryAttempts, deliveryID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deferDelivery = `-- name: DeferDelivery :exec
UPDATE deliveries SET next_retry_at = GREATEST(next_retry_at, $1::timestamptz)
WHERE id = $2 AND state = 'queued'
`

type DeferDeliveryParams struct {
	Until time.Time
	ID    string
}

// A row blocked behind an earlier version is due no sooner than it
// (the outbox scan then does not take it for a stuck message).
func (q *Queries) DeferDelivery(ctx context.Context, arg DeferDeliveryParams) error {
	_, err := q.db.Exec(ctx, deferDelivery, arg.Until, arg.ID)
	return err
}

const deliveryChannels = `-- name: DeliveryChannels :many
SELECT kind, state, attempt, last_attempt_at, status_code, next_retry_at
FROM deliveries
WHERE restriction_id = $1 AND ansp_version = $2
ORDER BY queued_at
LIMIT 300
`

type DeliveryChannelsParams struct {
	RestrictionID *string
	AnspVersion   *int64
}

type DeliveryChannelsRow struct {
	Kind          DeliveryKind
	State         DeliveryState
	Attempt       int32
	LastAttemptAt *time.Time
	StatusCode    *int32
	NextRetryAt   time.Time
}

func (q *Queries) DeliveryChannels(ctx context.Context, arg DeliveryChannelsParams) ([]DeliveryChannelsRow, error) {
	rows, err := q.db.Query(ctx, deliveryChannels, arg.RestrictionID, arg.AnspVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryChannelsRow{}
	for rows.Next() {
		var i DeliveryChannelsRow
		if err := rows.Scan(
			&i.Kind,
			&i.State,
			&i.Attempt,
			&i.LastAttemptAt,
			&i.StatusCode,
			&i.NextRetryAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deliveryClaimState = `-- name: DeliveryClaimState :one
SELECT d.state, d.lease_until, d.next_retry_at, clock_timestamp()::timestamptz AS now,
       -- the epoch when nothing earlier is queued
       COALESCE((SELECT min(GREATEST(p.next_retry_at, COALESCE(p.lease_until, p.next_retry_at)))
        FROM deliveries p
        WHERE (p.kind = d.kind OR (p.kind IN ('dss_put', 'dss_delete') AND d.kind IN ('dss_put', 'dss_delete')))
          AND p.restriction_id = d.restriction_id AND p.target = d.target
          AND p.ansp_version < d.ansp_version AND p.state = 'queued'), 'epoch'::timestamptz)::timestamptz AS blocked_until
FROM deliveries d WHERE d.id = $1
`

type DeliveryClaimStateRow struct {
	State        DeliveryState
	LeaseUntil   *time.Time
	NextRetryAt  time.Time
	Now          time.Time
	BlockedUntil time.Time
}

// Why a claim did not lease the row: its state, lease, due time and the
// soonest due time of an earlier version still queued.
func (q *Queries) DeliveryClaimState(ctx context.Context, id string) (DeliveryClaimStateRow, error) {
	row := q.db.QueryRow(ctx, deliveryClaimState, id)
	var i DeliveryClaimStateRow
	err := row.Scan(
		&i.State,
		&i.LeaseUntil,
		&i.NextRetryAt,
		&i.Now,
		&i.BlockedUntil,
	)
	return i, err
}

const deliveryVersion = `-- name: DeliveryVersion :one
SELECT r.id, r.ansp_ref, r.identifier, r.uspace_airspace_id, r.state AS current_state, r.ansp_version AS current_version,
       r.published_version, v.version, v.state, v.starts_at, v.ends_at, v.feature::text AS feature, v.changed_at,
       r.dss_state, r.dss_pending_since, r.dss_put_version, r.dss_version,
       COALESCE((SELECT p.state::text FROM restriction_versions p
                 WHERE p.restriction_id = r.id AND p.version = v.version - 1), '')::text AS prev_state
FROM restrictions r
JOIN restriction_versions v ON v.restriction_id = r.id
 AND v.version = CASE WHEN $1::bigint = 0 THEN r.ansp_version ELSE $1::bigint END
WHERE r.id = $2
`

type DeliveryVersionParams struct {
	Version int64
	ID      string
}

type DeliveryVersionRow struct {
	ID               string
	AnspRef          string
	Identifier       string
	UspaceAirspaceID string
	CurrentState     RestrictionState
	CurrentVersion   int64
	PublishedVersion *int64
	Version          int64
	State            RestrictionState
	StartsAt         time.Time
	EndsAt           time.Time
	Feature          string
	ChangedAt        time.Time
	DssState         string
	DssPendingSince  *time.Time
	DssPutVersion    *int64
	DssVersion       *int64
	PrevState        string
}

// A version of a restriction (0: its current one) with what a delivery
// needs: the restriction now, the version's window and feature, and the
// state of the version before it.
func (q *Queries) DeliveryVersion(ctx context.Context, arg DeliveryVersionParams) (DeliveryVersionRow, error) {
	row := q.db.QueryRow(ctx, deliveryVersion, arg.Version, arg.ID)
	var i DeliveryVersionRow
	err := row.Scan(
		&i.ID,
		&i.AnspRef,
		&i.Identifier,
		&i.UspaceAirspaceID,
		&i.CurrentState,
		&i.CurrentVersion,
		&i.PublishedVersion,
		&i.Version,
		&i.State,
		&i.StartsAt,
		&i.EndsAt,
		&i.Feature,
		&i.ChangedAt,
		&i.DssState,
		&i.DssPendingSince,
		&i.DssPutVersion,
		&i.DssVersion,
		&i.PrevState,
	)
	return i, err
}

const expediteQueued = `-- name: ExpediteQueued :many
UPDATE deliveries SET next_retry_at = clock_timestamp()
WHERE kind = $1 AND restriction_id = $2 AND state = 'queued'
RETURNING id, kind, bus_seq
`

type ExpediteQueuedParams struct {
	Kind          DeliveryKind
	RestrictionID *string
}

type ExpediteQueuedRow struct {
	ID     string
	Kind   DeliveryKind
	BusSeq int32
}

// The reconciliation: the queued rows of the restriction are due now.
func (q *Queries) ExpediteQueued(ctx context.Context, arg ExpediteQueuedParams) ([]ExpediteQueuedRow, error) {
	rows, err := q.db.Query(ctx, expediteQueued, arg.Kind, arg.RestrictionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpediteQueuedRow{}
	for rows.Next() {
		var i ExpediteQueuedRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.BusSeq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishDelivery = `-- name: FinishDelivery :one
UPDATE deliveries SET
    state = $1, lease_token = NULL, lease_until = NULL,
    status_code = $2, response_excerpt = $3, last_error = $4,
    sent_at = CASE WHEN $1::delivery_state = 'sent' THEN clock_timestamp() ELSE sent_at END,
    next_retry_at = CASE WHEN $1::delivery_state = 'queued' THEN $5::timestamptz ELSE next_retry_at END,
    cancel_reason = $6
WHERE id = $7 AND lease_token = $8 AND state = 'queued'
RETURNING id
`

type FinishDeliveryParams struct {
	State           DeliveryState
	StatusCode      *int32
	ResponseExcerpt *string
	LastError       *string
	RetryAt         time.Time
	CancelReason    *string
	ID              string
	Token           *string
}

// The outcome of an attempt, only while the lease is still this
// attempt's.
func (q *Queries) FinishDelivery(ctx context.Context, arg FinishDeliveryParams) (string, error) {
	row := q.db.QueryRow(ctx, finishDelivery,
		arg.State,
		arg.StatusCode,
		arg.ResponseExcerpt,
		arg.LastError,
		arg.RetryAt,
		arg.CancelReason,
		arg.ID,
		arg.Token,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertAlarm = `-- name: InsertAlarm :one
INSERT INTO delivery_alarms (id, kind, restriction_id, ansp_version, delivery_id, raised_at, since, detail)
VALUES ($1, $2, $3, $4, $5,
        clock_timestamp(), $6, $7)
ON CONFLICT DO NOTHING
RETURNING id, kind, restriction_id, ansp_version, delivery_id, raised_at, since, detail, cleared_at, clear_reason, acknowledged_by, acknowledged_at, ack_reason
`

type InsertAlarmParams struct {
	ID            string
	Kind          string
	RestrictionID *string
	AnspVersion   *int64
	DeliveryID    *string
	Since         time.Time
	Detail        string
}

// No row back: an equal alarm is open (one cisp_not_published per
// restriction, one alarm per delivery and kind).
func (q *Queries) InsertAlarm(ctx context.Context, arg InsertAlarmParams) (DeliveryAlarm, error) {
	row := q.db.QueryRow(ctx, insertAlarm,
		arg.ID,
		arg.Kind,
		arg.RestrictionID,
		arg.AnspVersion,
		arg.DeliveryID,
		arg.Since,
		arg.Detail,
	)
	var i DeliveryAlarm
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RestrictionID,
		&i.AnspVersion,
		&i.DeliveryID,
		&i.RaisedAt,
		&i.Since,
		&i.Detail,
		&i.ClearedAt,
		&i.ClearReason,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.AckReason,
	)
	return i, err
}

const insertDelivery = `-- name: InsertDelivery :one

INSERT INTO deliveries (id, kind, subject_ref, restriction_id, ansp_version, op, target, idempotency_key,
                        max_attempts, queued_at, window_ends_at, next_retry_at, body, policy_version)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9, clock_timestamp(),
        clock_timestamp() + make_interval(secs => $10::float8), clock_timestamp(),
        $11, $12)
ON CONFLICT ON CONSTRAINT deliveries_unique_job DO NOTHING
RETURNING id
`

type InsertDeliveryParams struct {
	ID             string
	Kind           DeliveryKind
	SubjectRef     string
	RestrictionID  *string
	AnspVersion    *int64
	Op             string
	Target         string
	IdempotencyKey string
	MaxAttempts    int32
	WindowS        float64
	Body           []byte
	PolicyVersion  *int64
}

// WP-8: the outbox (internal/deliver). Every instant is the database's
// clock (clock_timestamp()), never a replica's.
// A queued job; no row back means the same job (kind, idempotency key,
// target) exists already.
func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) (string, error) {
	row := q.db.QueryRow(ctx, insertDelivery,
		arg.ID,
		arg.Kind,
		arg.SubjectRef,
		arg.RestrictionID,
		arg.AnspVersion,
		arg.Op,
		arg.Target,
		arg.IdempotencyKey,
		arg.MaxAttempts,
		arg.WindowS,
		arg.Body,
		arg.PolicyVersion,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertDeliveryAttempt = `-- name: InsertDeliveryAttempt :exec
INSERT INTO delivery_attempts (delivery_id, attempt, at, duration_ms, status_code, outcome, error, response_excerpt)
VALUES ($1, $2, clock_timestamp(), $3, $4,
        $5, $6, $7)
ON CONFLICT (delivery_id, attempt) DO NOTHING
`

type InsertDeliveryAttemptParams struct {
	DeliveryID      string
	Attempt         int32
	DurationMs      int32
	StatusCode      *int32
	Outcome         string
	Error           *string
	ResponseExcerpt *string
}

func (q *Queries) InsertDeliveryAttempt(ctx context.Context, arg InsertDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, insertDeliveryAttempt,
		arg.DeliveryID,
		arg.Attempt,
		arg.DurationMs,
		arg.StatusCode,
		arg.Outcome,
		arg.Error,
		arg.ResponseExcerpt,
	)
	return err
}

const listAlarms = `-- name: ListAlarms :many
SELECT id, kind, restriction_id, ansp_version, delivery_id, raised_at, since, detail, cleared_at, clear_reason, acknowledged_by, acknowledged_at, ack_reason FROM delivery_alarms
WHERE $1::boolean OR cleared_at IS NULL
ORDER BY raised_at DESC, id DESC
LIMIT $2
`

type ListAlarmsParams struct {
	AllAlarms bool
	PageSize  int32
}

func (q *Queries) ListAlarms(ctx context.Context, arg ListAlarmsParams) ([]DeliveryAlarm, error) {
	rows, err := q.db.Query(ctx, listAlarms, arg.AllAlarms, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryAlarm{}
	for rows.Next() {
		var i DeliveryAlarm
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.RestrictionID,
			&i.AnspVersion,
			&i.DeliveryID,
			&i.RaisedAt,
			&i.Since,
			&i.Detail,
			&i.ClearedAt,
			&i.ClearReason,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.AckReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryBusPublished = `-- name: MarkDeliveryBusPublished :one
UPDATE deliveries SET bus_seq = $1, bus_published_at = clock_timestamp()
WHERE id = $2 AND bus_seq = $1::integer - 1
RETURNING id
`

type MarkDeliveryBusPublishedParams struct {
	Seq int32
	ID  string
}

func (q *Queries) MarkDeliveryBusPublished(ctx context.Context, arg MarkDeliveryBusPublishedParams) (string, error) {
	row := q.db.QueryRow(ctx, markDeliveryBusPublished, arg.Seq, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const markPublishedVersion = `-- name: MarkPublishedVersion :one
UPDATE restrictions SET published_version = GREATEST(COALESCE(published_version, 0), $1::bigint)
WHERE id = $2 AND $1::bigint <= ansp_version
RETURNING state, ansp_version, published_version
`

type MarkPublishedVersionParams struct {
	Version int64
	ID      string
}

type MarkPublishedVersionRow struct {
	State            RestrictionState
	AnspVersion      int64
	PublishedVersion *int64
}

// The CISP confirmed version: published_version never moves back.
func (q *Queries) MarkPublishedVersion(ctx context.Context, arg MarkPublishedVersionParams) (MarkPublishedVersionRow, error) {
	row := q.db.QueryRow(ctx, markPublishedVersion, arg.Version, arg.ID)
	var i MarkPublishedVersionRow
	err := row.Scan(&i.State, &i.AnspVersion, &i.PublishedVersion)
	return i, err
}

const openCISPAlarm = `-- name: OpenCISPAlarm :one
SELECT id, kind, restriction_id, ansp_version, delivery_id, raised_at, since, detail, cleared_at, clear_reason, acknowledged_by, acknowledged_at, ack_reason FROM delivery_alarms
WHERE restriction_id = $1 AND kind = 'cisp_not_published' AND cleared_at IS NULL
`

func (q *Queries) OpenCISPAlarm(ctx context.Context, restrictionID *string) (DeliveryAlarm, error) {
	row := q.db.QueryRow(ctx, openCISPAlarm, restrictionID)
	var i DeliveryAlarm
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RestrictionID,
		&i.AnspVersion,
		&i.DeliveryID,
		&i.RaisedAt,
		&i.Since,
		&i.Detail,
		&i.ClearedAt,
		&i.ClearReason,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.AckReason,
	)
	return i, err
}

const overdueRestrictions = `-- name: OverdueRestrictions :many
SELECT r.id, r.ansp_version, v.changed_at,
       COALESCE((SELECT a.id FROM delivery_alarms a
                 WHERE a.restriction_id = r.id AND a.kind = 'cisp_not_published' AND a.cleared_at IS NULL), '')::text AS alarm_id
FROM restrictions r
JOIN restriction_versions v ON v.restriction_id = r.id AND v.version = r.ansp_version
WHERE r.state = 'active' AND COALESCE(r.published_version, 0) < r.ansp_version
  AND v.changed_at <= clock_timestamp() - make_interval(secs => $1::float8)
  AND NOT EXISTS (SELECT 1 FROM delivery_alarms a
                  WHERE a.restriction_id = r.id AND a.kind = 'cisp_not_published' AND a.cleared_at IS NULL
                    AND a.ansp_version >= r.ansp_version)
ORDER BY v.changed_at
LIMIT $2
`

type OverdueRestrictionsParams struct {
	AfterS   float64
	PageSize int32
}

type OverdueRestrictionsRow struct {
	ID          string
	AnspVersion int64
	ChangedAt   time.Time
	AlarmID     string
}

// Active restrictions whose current version is not published to the
// CISP for longer than after_s, without an open alarm at that version.
func (q *Queries) OverdueRestrictions(ctx context.Context, arg OverdueRestrictionsParams) ([]OverdueRestrictionsRow, error) {
	rows, err := q.db.Query(ctx, overdueRestrictions, arg.AfterS, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OverdueRestrictionsRow{}
	for rows.Next() {
		var i OverdueRestrictionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AnspVersion,
			&i.ChangedAt,
			&i.AlarmID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingDeliveries = `-- name: PendingDeliveries :many
SELECT id, kind, bus_seq, (bus_published_at IS NOT NULL)::boolean AS stuck
FROM deliveries
WHERE state = 'queued' AND (lease_until IS NULL OR lease_until < clock_timestamp()) AND (
      (bus_published_at IS NULL AND queued_at < clock_timestamp() - make_interval(secs => $1::float8))
   OR (bus_published_at IS NOT NULL
       AND next_retry_at < clock_timestamp() - make_interval(secs => $2::float8)
       AND GREATEST(bus_published_at, COALESCE(last_attempt_at, bus_published_at)) < clock_timestamp() - make_interval(secs => $2::float8)))
ORDER BY next_retry_at
LIMIT $3
`

type PendingDeliveriesParams struct {
	PublishGraceS float64
	StuckGraceS   float64
	PageSize      int32
}

type PendingDeliveriesRow struct {
	ID     string
	Kind   DeliveryKind
	BusSeq int32
	Stuck  bool
}

// Queued rows never published (older than the publish grace), and rows
// whose message is overdue: due for longer than the stuck grace with no
// attempt and no publish since.
func (q *Queries) PendingDeliveries(ctx context.Context, arg PendingDeliveriesParams) ([]PendingDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, pendingDeliveries, arg.PublishGraceS, arg.StuckGraceS, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingDeliveriesRow{}
	for rows.Next() {
		var i PendingDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.BusSeq,
			&i.Stuck,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const prepareDelivery = `-- name: PrepareDelivery :one
UPDATE deliveries SET
    method = COALESCE(method, $1), url = COALESCE(url, $2), body = COALESCE(body, $3)
WHERE id = $4 AND lease_token = $5
RETURNING id, kind, subject_ref, restriction_id, ansp_version, op, target, idempotency_key, state,
          attempt, max_attempts, queued_at, window_ends_at, next_retry_at, bus_seq, last_attempt_at,
          sent_at, status_code, response_excerpt, last_error, method, url, body, cancel_reason
`

type PrepareDeliveryParams struct {
	Method *string
	Url    *string
	Body   []byte
	ID     string
	Token  *string
}

type PrepareDeliveryRow struct {
	ID              string
	Kind            DeliveryKind
	SubjectRef      string
	RestrictionID   *string
	AnspVersion     *int64
	Op              string
	Target          string
	IdempotencyKey  string
	State           DeliveryState
	Attempt         int32
	MaxAttempts     int32
	QueuedAt        time.Time
	WindowEndsAt    time.Time
	NextRetryAt     time.Time
	BusSeq          int32
	LastAttemptAt   *time.Time
	SentAt          *time.Time
	StatusCode      *int32
	ResponseExcerpt *string
	LastError       *string
	Method          *string
	Url             *string
	Body            []byte
	CancelReason    *string
}

// Fixes the request at the first attempt; a prepared row keeps its own.
func (q *Queries) PrepareDelivery(ctx context.Context, arg PrepareDeliveryParams) (PrepareDeliveryRow, error) {
	row := q.db.QueryRow(ctx, prepareDelivery,
		arg.Method,
		arg.Url,
		arg.Body,
		arg.ID,
		arg.Token,
	)
	var i PrepareDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SubjectRef,
		&i.RestrictionID,
		&i.AnspVersion,
		&i.Op,
		&i.Target,
		&i.IdempotencyKey,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.QueuedAt,
		&i.WindowEndsAt,
		&i.NextRetryAt,
		&i.BusSeq,
		&i.LastAttemptAt,
		&i.SentAt,
		&i.StatusCode,
		&i.ResponseExcerpt,
		&i.LastError,
		&i.Method,
		&i.Url,
		&i.Body,
		&i.CancelReason,
	)
	return i, err
}

const queuedOfVersion = `-- name: QueuedOfVersion :many
SELECT id, kind, bus_seq FROM deliveries
WHERE restriction_id = $1 AND ansp_version = $2
  AND state = 'queued' AND bus_published_at IS NULL
ORDER BY id
LIMIT 300
`

type QueuedOfVersionParams struct {
	RestrictionID *string
	AnspVersion   *int64
}

type QueuedOfVersionRow struct {
	ID     string
	Kind   DeliveryKind
	BusSeq int32
}

func (q *Queries) QueuedOfVersion(ctx context.Context, arg QueuedOfVersionParams) ([]QueuedOfVersionRow, error) {
	rows, err := q.db.Query(ctx, queuedOfVersion, arg.RestrictionID, arg.AnspVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueuedOfVersionRow{}
	for rows.Next() {
		var i QueuedOfVersionRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.BusSeq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueAbandoned = `-- name: RequeueAbandoned :one
UPDATE deliveries SET state = 'queued', max_attempts = LEAST(attempt + $1::integer, 100000),
    window_ends_at = clock_timestamp() + make_interval(secs => $2::float8),
    next_retry_at = clock_timestamp(), lease_token = NULL, lease_until = NULL
WHERE kind = $3 AND restriction_id = $4 AND ansp_version = $5
  AND state = 'abandoned'
RETURNING id, kind, bus_seq
`

type RequeueAbandonedParams struct {
	Extra         int32
	WindowS       float64
	Kind          DeliveryKind
	RestrictionID *string
	AnspVersion   *int64
}

type RequeueAbandonedRow struct {
	ID     string
	Kind   DeliveryKind
	BusSeq int32
}

func (q *Queries) RequeueAbandoned(ctx context.Context, arg RequeueAbandonedParams) (RequeueAbandonedRow, error) {
	row := q.db.QueryRow(ctx, requeueAbandoned,
		arg.Extra,
		arg.WindowS,
		arg.Kind,
		arg.RestrictionID,
		arg.AnspVersion,
	)
	var i RequeueAbandonedRow
	err := row.Scan(&i.ID, &i.Kind, &i.BusSeq)
	return i, err
}

const unpublishedActive = `-- name: UnpublishedActive :many
SELECT id, ansp_ref, ansp_version FROM restrictions
WHERE state = 'active' AND COALESCE(published_version, 0) < ansp_version
ORDER BY id
LIMIT $1
`

type UnpublishedActiveRow struct {
	ID          string
	AnspRef     string
	AnspVersion int64
}

func (q *Queries) UnpublishedActive(ctx context.Context, pageSize int32) ([]UnpublishedActiveRow, error) {
	rows, err := q.db.Query(ctx, unpublishedActive, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnpublishedActiveRow{}
	for rows.Next() {
		var i UnpublishedActiveRow
		if err := rows.Scan(&i.ID, &i.AnspRef, &i.AnspVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
