// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dss.sql

package relational

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const cancelQueuedTo = `-- name: CancelQueuedTo :many
UPDATE deliveries SET state = 'cancelled', cancel_reason = $1, lease_token = NULL, lease_until = NULL
WHERE kind = $2 AND restriction_id = $3 AND target = $4
  AND ansp_version < $5 AND state = 'queued'
RETURNING id, target, ansp_version
`

type CancelQueuedToParams struct {
	Reason        *string
	Kind          DeliveryKind
	RestrictionID *string
	Target        string
	Below         *int64
}

type CancelQueuedToRow struct {
	ID          string
	Target      string
	AnspVersion *int64
}

func (q *Queries) CancelQueuedTo(ctx context.Context, arg CancelQueuedToParams) ([]CancelQueuedToRow, error) {
	rows, err := q.db.Query(ctx, cancelQueuedTo,
		arg.Reason,
		arg.Kind,
		arg.RestrictionID,
		arg.Target,
		arg.Below,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CancelQueuedToRow{}
	for rows.Next() {
		var i CancelQueuedToRow
		if err := rows.Scan(&i.ID, &i.Target, &i.AnspVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearAlarm = `-- name: ClearAlarm :one
UPDATE delivery_alarms SET cleared_at = clock_timestamp(), clear_reason = $1
WHERE id = $2 AND cleared_at IS NULL
RETURNING id, kind, restriction_id, ansp_version, delivery_id, raised_at, since, detail, cleared_at, clear_reason, acknowledged_by, acknowledged_at, ack_reason
`

type ClearAlarmParams struct {
	Reason *string
	ID     string
}

func (q *Queries) ClearAlarm(ctx context.Context, arg ClearAlarmParams) (DeliveryAlarm, error) {
	row := q.db.QueryRow(ctx, clearAlarm, arg.Reason, arg.ID)
	var i DeliveryAlarm
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RestrictionID,
		&i.AnspVersion,
		&i.DeliveryID,
		&i.RaisedAt,
		&i.Since,
		&i.Detail,
		&i.ClearedAt,
		&i.ClearReason,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.AckReason,
	)
	return i, err
}

const clearableLateAlarms = `-- name: ClearableLateAlarms :many
SELECT a.id, a.delivery_id, d.state
FROM delivery_alarms a JOIN deliveries d ON d.id = a.delivery_id
WHERE a.kind = 'uss_notify_late' AND a.cleared_at IS NULL AND d.state <> 'queued'
ORDER BY a.raised_at
LIMIT $1
`

type ClearableLateAlarmsRow struct {
	ID         string
	DeliveryID *string
	State      DeliveryState
}

func (q *Queries) ClearableLateAlarms(ctx context.Context, pageSize int32) ([]ClearableLateAlarmsRow, error) {
	rows, err := q.db.Query(ctx, clearableLateAlarms, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClearableLateAlarmsRow{}
	for rows.Next() {
		var i ClearableLateAlarmsRow
		if err := rows.Scan(&i.ID, &i.DeliveryID, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dSSBacklog = `-- name: DSSBacklog :one
SELECT count(*)::bigint AS n, COALESCE(min(queued_at), 'epoch'::timestamptz)::timestamptz AS oldest
FROM deliveries WHERE kind IN ('dss_put', 'dss_delete') AND state = 'queued'
`

type DSSBacklogRow struct {
	N      int64
	Oldest time.Time
}

func (q *Queries) DSSBacklog(ctx context.Context) (DSSBacklogRow, error) {
	row := q.db.QueryRow(ctx, dSSBacklog)
	var i DSSBacklogRow
	err := row.Scan(&i.N, &i.Oldest)
	return i, err
}

const dSSInfo = `-- name: DSSInfo :one

SELECT r.id, r.ansp_ref, r.dss_constraint_id, r.dss_ovn, r.state AS current_state, v.version, v."constraint"
FROM restrictions r
JOIN restriction_versions v ON v.restriction_id = r.id AND v.version = $1::bigint
WHERE r.id = $2
`

type DSSInfoParams struct {
	Version int64
	ID      string
}

type DSSInfoRow struct {
	ID              string
	AnspRef         string
	DssConstraintID *uuid.UUID
	DssOvn          *string
	CurrentState    RestrictionState
	Version         int64
	Constraint      json.RawMessage
}

// WP-9: the F3548 constraint manager (internal/dss, the DSS channel of
// internal/deliver). Every instant is the database's clock.
// What a DSS job of a version reads at its attempt.
func (q *Queries) DSSInfo(ctx context.Context, arg DSSInfoParams) (DSSInfoRow, error) {
	row := q.db.QueryRow(ctx, dSSInfo, arg.Version, arg.ID)
	var i DSSInfoRow
	err := row.Scan(
		&i.ID,
		&i.AnspRef,
		&i.DssConstraintID,
		&i.DssOvn,
		&i.CurrentState,
		&i.Version,
		&i.Constraint,
	)
	return i, err
}

const dSSNotificationJob = `-- name: DSSNotificationJob :many
SELECT n.constraint_id, n.op, n.subscription_id, n.notification_index,
       w.reference, (v."constraint" -> 'details')::jsonb AS details
FROM dss_notifications n
LEFT JOIN dss_constraint_writes w ON w.restriction_id = n.restriction_id AND w.ansp_version = n.ansp_version AND w.op = n.op
LEFT JOIN restriction_versions v ON v.restriction_id = n.restriction_id AND v.version = n.ansp_version
WHERE n.delivery_id = $1
ORDER BY n.subscription_id
LIMIT 10001
`

type DSSNotificationJobRow struct {
	ConstraintID      uuid.UUID
	Op                string
	SubscriptionID    uuid.UUID
	NotificationIndex int32
	Reference         json.RawMessage
	Details           json.RawMessage
}

// A uss_notify job's subscriptions with the write it reports: the
// reference the DSS answered and the details of that version.
func (q *Queries) DSSNotificationJob(ctx context.Context, deliveryID string) ([]DSSNotificationJobRow, error) {
	rows, err := q.db.Query(ctx, dSSNotificationJob, deliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DSSNotificationJobRow{}
	for rows.Next() {
		var i DSSNotificationJobRow
		if err := rows.Scan(
			&i.ConstraintID,
			&i.Op,
			&i.SubscriptionID,
			&i.NotificationIndex,
			&i.Reference,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDSSNotification = `-- name: InsertDSSNotification :exec
INSERT INTO dss_notifications (delivery_id, subscription_id, notification_index, restriction_id, ansp_version,
                               constraint_id, subscriber, op, dss_answered_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8, clock_timestamp())
ON CONFLICT (delivery_id, subscription_id) DO NOTHING
`

type InsertDSSNotificationParams struct {
	DeliveryID        string
	SubscriptionID    uuid.UUID
	NotificationIndex int32
	RestrictionID     string
	AnspVersion       int64
	ConstraintID      uuid.UUID
	Subscriber        string
	Op                string
}

func (q *Queries) InsertDSSNotification(ctx context.Context, arg InsertDSSNotificationParams) error {
	_, err := q.db.Exec(ctx, insertDSSNotification,
		arg.DeliveryID,
		arg.SubscriptionID,
		arg.NotificationIndex,
		arg.RestrictionID,
		arg.AnspVersion,
		arg.ConstraintID,
		arg.Subscriber,
		arg.Op,
	)
	return err
}

const insertDSSWrite = `-- name: InsertDSSWrite :exec
INSERT INTO dss_constraint_writes (restriction_id, ansp_version, op, delivery_id, constraint_id, ovn, dss_version, reference, subscribers)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9)
ON CONFLICT (restriction_id, ansp_version, op) DO NOTHING
`

type InsertDSSWriteParams struct {
	RestrictionID string
	AnspVersion   int64
	Op            string
	DeliveryID    string
	ConstraintID  uuid.UUID
	Ovn           *string
	DssVersion    *int64
	Reference     json.RawMessage
	Subscribers   int32
}

func (q *Queries) InsertDSSWrite(ctx context.Context, arg InsertDSSWriteParams) error {
	_, err := q.db.Exec(ctx, insertDSSWrite,
		arg.RestrictionID,
		arg.AnspVersion,
		arg.Op,
		arg.DeliveryID,
		arg.ConstraintID,
		arg.Ovn,
		arg.DssVersion,
		arg.Reference,
		arg.Subscribers,
	)
	return err
}

const lateNotifications = `-- name: LateNotifications :many
SELECT d.id, d.restriction_id, d.ansp_version, d.target, d.queued_at
FROM deliveries d
WHERE d.kind = 'uss_notify' AND d.state = 'queued'
  AND d.queued_at <= clock_timestamp() - make_interval(secs => $1::float8)
  AND NOT EXISTS (SELECT 1 FROM delivery_alarms a WHERE a.delivery_id = d.id AND a.kind = 'uss_notify_late')
ORDER BY d.queued_at
LIMIT $2
`

type LateNotificationsParams struct {
	LatencyS float64
	PageSize int32
}

type LateNotificationsRow struct {
	ID            string
	RestrictionID *string
	AnspVersion   *int64
	Target        string
	QueuedAt      time.Time
}

// Subscriber notifications still queued latency_s after the DSS
// answered (their queuing), with no uss_notify_late alarm yet.
func (q *Queries) LateNotifications(ctx context.Context, arg LateNotificationsParams) ([]LateNotificationsRow, error) {
	rows, err := q.db.Query(ctx, lateNotifications, arg.LatencyS, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LateNotificationsRow{}
	for rows.Next() {
		var i LateNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.RestrictionID,
			&i.AnspVersion,
			&i.Target,
			&i.QueuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDSSDelete = `-- name: RecordDSSDelete :exec
UPDATE restrictions SET dss_ovn = NULL, dss_written_at = clock_timestamp()
WHERE id = $1
`

// The DSS deleted the reference (or held none): no ovn is held any more;
// the reference stays for the details' retention.
func (q *Queries) RecordDSSDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, recordDSSDelete, id)
	return err
}

const recordDSSPut = `-- name: RecordDSSPut :exec
UPDATE restrictions SET
    dss_ovn = $1, dss_version = $2, dss_reference = $3,
    dss_put_version = $4::bigint, dss_written_at = clock_timestamp()
WHERE id = $5 AND COALESCE(dss_put_version, 0) <= $4::bigint
`

type RecordDSSPutParams struct {
	Ovn        *string
	DssVersion *int64
	Reference  json.RawMessage
	Version    int64
	ID         string
}

// The DSS accepted a put of version: its ovn, version and reference are
// the restriction's (a put of an older version never replaces a newer).
func (q *Queries) RecordDSSPut(ctx context.Context, arg RecordDSSPutParams) error {
	_, err := q.db.Exec(ctx, recordDSSPut,
		arg.Ovn,
		arg.DssVersion,
		arg.Reference,
		arg.Version,
		arg.ID,
	)
	return err
}

const settleDSS = `-- name: SettleDSS :exec
WITH q AS (
    SELECT EXISTS (SELECT 1 FROM deliveries d
                   WHERE d.restriction_id = $2 AND d.kind IN ('dss_put', 'dss_delete') AND d.state = 'queued') AS pending
)
UPDATE restrictions r SET
    dss_state = CASE WHEN q.pending THEN 'pending'
                     WHEN $1::boolean THEN 'failed'
                     WHEN r.dss_ovn IS NOT NULL THEN 'written'
                     WHEN r.dss_reference IS NOT NULL THEN 'deleted'
                     ELSE 'none' END,
    dss_pending_since = CASE WHEN q.pending OR $1::boolean
                             THEN COALESCE(r.dss_pending_since, clock_timestamp()) ELSE NULL END
FROM q
WHERE r.id = $2
`

type SettleDSSParams struct {
	Failed bool
	ID     string
}

// The restriction's standing in the DSS from what is queued and what
// was written: pending while a DSS write is queued (since the first time
// it was), failed when the caller says so, else written (an ovn held),
// deleted (a reference written, no ovn), or none.
func (q *Queries) SettleDSS(ctx context.Context, arg SettleDSSParams) error {
	_, err := q.db.Exec(ctx, settleDSS, arg.Failed, arg.ID)
	return err
}

const settleDSSNotifications = `-- name: SettleDSSNotifications :exec
UPDATE dss_notifications SET
    status = $1,
    sent_at = CASE WHEN $1::text = 'sent' THEN clock_timestamp() ELSE NULL END
WHERE delivery_id = $2 AND status = 'queued'
`

type SettleDSSNotificationsParams struct {
	Status     string
	DeliveryID string
}

func (q *Queries) SettleDSSNotifications(ctx context.Context, arg SettleDSSNotificationsParams) error {
	_, err := q.db.Exec(ctx, settleDSSNotifications, arg.Status, arg.DeliveryID)
	return err
}

const writtenConstraint = `-- name: WrittenConstraint :one
SELECT r.dss_reference::jsonb AS reference, (v."constraint" -> 'details')::jsonb AS details,
       (r.state IN ('ended', 'cancelled')
        AND COALESCE(r.ended_at_actual, r.ends_at) + make_interval(secs => $1::float8) < clock_timestamp())::boolean AS expired
FROM restrictions r
JOIN restriction_versions v ON v.restriction_id = r.id AND v.version = r.dss_put_version
WHERE r.dss_constraint_id = $2 AND r.dss_reference IS NOT NULL
`

type WrittenConstraintParams struct {
	RetentionS   float64
	ConstraintID *uuid.UUID
}

type WrittenConstraintRow struct {
	Reference json.RawMessage
	Details   json.RawMessage
	Expired   bool
}

// GET /uss/v1/constraints/{entityid}: the reference the DSS last
// accepted and the details of that version, and whether the restriction
// ended longer than retention_s ago.
func (q *Queries) WrittenConstraint(ctx context.Context, arg WrittenConstraintParams) (WrittenConstraintRow, error) {
	row := q.db.QueryRow(ctx, writtenConstraint, arg.RetentionS, arg.ConstraintID)
	var i WrittenConstraintRow
	err := row.Scan(&i.Reference, &i.Details, &i.Expired)
	return i, err
}
