// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package relational

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeliveryKind string

const (
	DeliveryKindCispPublish    DeliveryKind = "cisp_publish"
	DeliveryKindCispHeartbeat  DeliveryKind = "cisp_heartbeat"
	DeliveryKindDssPut         DeliveryKind = "dss_put"
	DeliveryKindDssDelete      DeliveryKind = "dss_delete"
	DeliveryKindUssNotify      DeliveryKind = "uss_notify"
	DeliveryKindDirectDegraded DeliveryKind = "direct_degraded"
	DeliveryKindOccurrence     DeliveryKind = "occurrence"
)

func (e *DeliveryKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryKind(s)
	case string:
		*e = DeliveryKind(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryKind: %T", src)
	}
	return nil
}

type NullDeliveryKind struct {
	DeliveryKind DeliveryKind
	Valid        bool // Valid is true if DeliveryKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryKind) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryKind), nil
}

func (e DeliveryKind) Valid() bool {
	switch e {
	case DeliveryKindCispPublish,
		DeliveryKindCispHeartbeat,
		DeliveryKindDssPut,
		DeliveryKindDssDelete,
		DeliveryKindUssNotify,
		DeliveryKindDirectDegraded,
		DeliveryKindOccurrence:
		return true
	}
	return false
}

func AllDeliveryKindValues() []DeliveryKind {
	return []DeliveryKind{
		DeliveryKindCispPublish,
		DeliveryKindCispHeartbeat,
		DeliveryKindDssPut,
		DeliveryKindDssDelete,
		DeliveryKindUssNotify,
		DeliveryKindDirectDegraded,
		DeliveryKindOccurrence,
	}
}

type DeliveryState string

const (
	DeliveryStateQueued    DeliveryState = "queued"
	DeliveryStateSent      DeliveryState = "sent"
	DeliveryStateFailed    DeliveryState = "failed"
	DeliveryStateAbandoned DeliveryState = "abandoned"
	DeliveryStateCancelled DeliveryState = "cancelled"
)

func (e *DeliveryState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryState(s)
	case string:
		*e = DeliveryState(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryState: %T", src)
	}
	return nil
}

type NullDeliveryState struct {
	DeliveryState DeliveryState
	Valid         bool // Valid is true if DeliveryState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryState) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryState), nil
}

func (e DeliveryState) Valid() bool {
	switch e {
	case DeliveryStateQueued,
		DeliveryStateSent,
		DeliveryStateFailed,
		DeliveryStateAbandoned,
		DeliveryStateCancelled:
		return true
	}
	return false
}

func AllDeliveryStateValues() []DeliveryState {
	return []DeliveryState{
		DeliveryStateQueued,
		DeliveryStateSent,
		DeliveryStateFailed,
		DeliveryStateAbandoned,
		DeliveryStateCancelled,
	}
}

type RestrictionState string

const (
	RestrictionStatePlanned   RestrictionState = "planned"
	RestrictionStateActive    RestrictionState = "active"
	RestrictionStateEnded     RestrictionState = "ended"
	RestrictionStateCancelled RestrictionState = "cancelled"
)

func (e *RestrictionState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RestrictionState(s)
	case string:
		*e = RestrictionState(s)
	default:
		return fmt.Errorf("unsupported scan type for RestrictionState: %T", src)
	}
	return nil
}

type NullRestrictionState struct {
	RestrictionState RestrictionState
	Valid            bool // Valid is true if RestrictionState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRestrictionState) Scan(value interface{}) error {
	if value == nil {
		ns.RestrictionState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RestrictionState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRestrictionState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RestrictionState), nil
}

func (e RestrictionState) Valid() bool {
	switch e {
	case RestrictionStatePlanned,
		RestrictionStateActive,
		RestrictionStateEnded,
		RestrictionStateCancelled:
		return true
	}
	return false
}

func AllRestrictionStateValues() []RestrictionState {
	return []RestrictionState{
		RestrictionStatePlanned,
		RestrictionStateActive,
		RestrictionStateEnded,
		RestrictionStateCancelled,
	}
}

type Adapter struct {
	ID           string
	Kind         string
	DisplayName  string
	SourceClass  string
	Config       json.RawMessage
	Status       string
	LastFrameAt  *time.Time
	LastStatusAt *time.Time
	Counters     json.RawMessage
}

type AnspPolicy struct {
	PolicyVersion       int64
	FeedMarginLateralM  float64
	FeedMarginVerticalM float64
	StaleAfterS         float64
	SourceLivenessS     float64
	CispAlarmAfterS     float64
	CispHeartbeatS      float64
	CisReconcileS       float64
	CisStaleBoundS      float64
	NoticeEscalationS   float64
	DefaultZoneType     string
	Country             string
	ChangedBy           string
	ChangedAt           time.Time
}

type CisCache struct {
	Dataset      string
	Version      int64
	Etag         string
	FetchedAt    time.Time
	InstalledAt  time.Time
	CisUpdatedAt *time.Time
	Body         json.RawMessage
}

type CisNotificationsSeen struct {
	Issuer    string
	Jti       string
	SeenAt    time.Time
	ExpiresAt time.Time
}

type Delivery struct {
	ID              string
	Kind            DeliveryKind
	SubjectRef      string
	RestrictionID   *string
	AnspVersion     *int64
	Op              string
	Target          string
	IdempotencyKey  string
	State           DeliveryState
	Attempt         int32
	MaxAttempts     int32
	QueuedAt        time.Time
	WindowEndsAt    time.Time
	NextRetryAt     time.Time
	LeaseToken      *string
	LeaseUntil      *time.Time
	BusSeq          int32
	BusPublishedAt  *time.Time
	LastAttemptAt   *time.Time
	SentAt          *time.Time
	StatusCode      *int32
	ResponseExcerpt *string
	LastError       *string
	Method          *string
	Url             *string
	Body            []byte
	CancelReason    *string
	PolicyVersion   *int64
}

type DeliveryAlarm struct {
	ID             string
	Kind           string
	RestrictionID  *string
	AnspVersion    *int64
	DeliveryID     *string
	RaisedAt       time.Time
	Since          time.Time
	Detail         string
	ClearedAt      *time.Time
	ClearReason    *string
	AcknowledgedBy *string
	AcknowledgedAt *time.Time
	AckReason      *string
}

type DeliveryAttempt struct {
	DeliveryID      string
	Attempt         int32
	At              time.Time
	DurationMs      int32
	StatusCode      *int32
	Outcome         string
	Error           *string
	ResponseExcerpt *string
}

type DssConstraintWrite struct {
	RestrictionID string
	AnspVersion   int64
	Op            string
	DeliveryID    string
	ConstraintID  uuid.UUID
	Ovn           *string
	DssVersion    *int64
	Reference     json.RawMessage
	Subscribers   int32
	WrittenAt     time.Time
}

type DssNotification struct {
	DeliveryID        string
	SubscriptionID    uuid.UUID
	NotificationIndex int32
	RestrictionID     string
	AnspVersion       int64
	ConstraintID      uuid.UUID
	Subscriber        string
	Op                string
	DssAnsweredAt     time.Time
	SentAt            *time.Time
	Status            string
}

type Event struct {
	ID         int64
	Ts         time.Time
	ActorType  string
	ActorID    string
	Purpose    string
	EntityType string
	EntityID   string
	EventType  string
	Payload    json.RawMessage
	PrevHash   string
	Hash       string
}

type GooseDbVersionRelational struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    pgtype.Timestamp
}

type LoginChallenge struct {
	TokenHash string
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
	Attempts  int32
	UsedAt    *time.Time
	RemoteIp  string
}

type LoginLockout struct {
	Username    string
	Failures    int32
	LockedUntil *time.Time
	UpdatedAt   time.Time
}

type OauthClientsSeen struct {
	ClientID    string
	System      *string
	Issuer      string
	MtlsSubject *string
	FirstSeenAt time.Time
	LastSeenAt  time.Time
	ScopesSeen  []string
}

type Restriction struct {
	ID                string
	AnspRef           string
	Identifier        string
	UspaceAirspaceID  string
	ZoneType          string
	Geom              interface{}
	RadiusM           *float64
	LowerM            float64
	LowerRef          string
	UpperM            float64
	UpperRef          string
	StartsAt          time.Time
	EndsAt            time.Time
	ReasonText        string
	State             RestrictionState
	AnspVersion       int64
	CreatedBy         string
	ActivatedBy       *string
	EndedBy           *string
	CancelledBy       *string
	CreatedAt         time.Time
	ActivatedAt       *time.Time
	EndedAtActual     *time.Time
	RequestID         *string
	PublishedVersion  *int64
	DssConstraintID   *uuid.UUID
	DssOvn            *string
	DssVersion        *int64
	SupersedesID      *string
	ActivateAt        *time.Time
	BusVersion        int64
	IdempotencyActor  *string
	IdempotencyKey    *string
	IdempotencySha256 *string
	CisVersion        *string
	DssState          string
	DssPendingSince   *time.Time
	DssReference      json.RawMessage
	DssPutVersion     *int64
	DssWrittenAt      *time.Time
}

type RestrictionIdentifierKey struct {
	Singleton bool
	OffsetN   int64
}

type RestrictionRequest struct {
	ID             string
	Requester      string
	Source         string
	Payload        json.RawMessage
	ReceivedAt     time.Time
	State          string
	DecidedBy      *string
	DecidedAt      *time.Time
	DecisionReason *string
	RestrictionID  *string
	ClientRef      string
	PayloadSha256  string
}

type RestrictionVersion struct {
	RestrictionID string
	Version       int64
	Feature       json.RawMessage
	Constraint    json.RawMessage
	ChangedBy     string
	ChangedAt     time.Time
	ChangeReason  string
	State         RestrictionState
	StartsAt      time.Time
	EndsAt        time.Time
	MsgID         string
}

type SourceControl struct {
	SourceType string
	InstanceID *string
	Enabled    bool
	Reason     string
	Actor      string
	ChangedAt  time.Time
	Version    int64
	Epoch      uuid.UUID
}

type SourceControlEpoch struct {
	Singleton bool
	Epoch     uuid.UUID
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Role         string
	Status       string
	OidcSubject  *string
	CreatedAt    time.Time
	CreatedBy    string
	UpdatedAt    time.Time
	UpdatedBy    string
	LastLoginAt  *time.Time
}

type UserMfa struct {
	UserID     uuid.UUID
	KeyID      string
	SecretEnc  []byte
	EnrolledAt *time.Time
	LastStep   int64
	UpdatedAt  time.Time
}

type UserSession struct {
	Jti          string
	UserID       uuid.UUID
	Role         string
	IssuedAt     time.Time
	ExpiresAt    time.Time
	LastSeenAt   time.Time
	RevokedAt    *time.Time
	RevokeReason *string
	RemoteIp     string
	UserAgent    string
}
