// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policy.sql

package relational

import (
	"context"
)

const insertPolicy = `-- name: InsertPolicy :one
INSERT INTO ansp_policy (
    feed_margin_lateral_m, feed_margin_vertical_m, stale_after_s,
    source_liveness_s, cisp_alarm_after_s, cisp_heartbeat_s,
    cis_reconcile_s, cis_stale_bound_s, notice_escalation_s,
    default_zone_type, country, changed_by, changed_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, clock_timestamp()
)
RETURNING policy_version, feed_margin_lateral_m, feed_margin_vertical_m, stale_after_s, source_liveness_s, cisp_alarm_after_s, cisp_heartbeat_s, cis_reconcile_s, cis_stale_bound_s, notice_escalation_s, default_zone_type, country, changed_by, changed_at
`

type InsertPolicyParams struct {
	FeedMarginLateralM  float64
	FeedMarginVerticalM float64
	StaleAfterS         float64
	SourceLivenessS     float64
	CispAlarmAfterS     float64
	CispHeartbeatS      float64
	CisReconcileS       float64
	CisStaleBoundS      float64
	NoticeEscalationS   float64
	DefaultZoneType     string
	Country             string
	ChangedBy           string
}

func (q *Queries) InsertPolicy(ctx context.Context, arg InsertPolicyParams) (AnspPolicy, error) {
	row := q.db.QueryRow(ctx, insertPolicy,
		arg.FeedMarginLateralM,
		arg.FeedMarginVerticalM,
		arg.StaleAfterS,
		arg.SourceLivenessS,
		arg.CispAlarmAfterS,
		arg.CispHeartbeatS,
		arg.CisReconcileS,
		arg.CisStaleBoundS,
		arg.NoticeEscalationS,
		arg.DefaultZoneType,
		arg.Country,
		arg.ChangedBy,
	)
	var i AnspPolicy
	err := row.Scan(
		&i.PolicyVersion,
		&i.FeedMarginLateralM,
		&i.FeedMarginVerticalM,
		&i.StaleAfterS,
		&i.SourceLivenessS,
		&i.CispAlarmAfterS,
		&i.CispHeartbeatS,
		&i.CisReconcileS,
		&i.CisStaleBoundS,
		&i.NoticeEscalationS,
		&i.DefaultZoneType,
		&i.Country,
		&i.ChangedBy,
		&i.ChangedAt,
	)
	return i, err
}

const latestPolicy = `-- name: LatestPolicy :one

SELECT policy_version, feed_margin_lateral_m, feed_margin_vertical_m, stale_after_s, source_liveness_s, cisp_alarm_after_s, cisp_heartbeat_s, cis_reconcile_s, cis_stale_bound_s, notice_escalation_s, default_zone_type, country, changed_by, changed_at FROM ansp_policy ORDER BY policy_version DESC LIMIT 1
`

// WP-1: the ansp_policy rows (internal/policy through store.PolicyRepo).
func (q *Queries) LatestPolicy(ctx context.Context) (AnspPolicy, error) {
	row := q.db.QueryRow(ctx, latestPolicy)
	var i AnspPolicy
	err := row.Scan(
		&i.PolicyVersion,
		&i.FeedMarginLateralM,
		&i.FeedMarginVerticalM,
		&i.StaleAfterS,
		&i.SourceLivenessS,
		&i.CispAlarmAfterS,
		&i.CispHeartbeatS,
		&i.CisReconcileS,
		&i.CisStaleBoundS,
		&i.NoticeEscalationS,
		&i.DefaultZoneType,
		&i.Country,
		&i.ChangedBy,
		&i.ChangedAt,
	)
	return i, err
}
