// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: restriction_lifecycle.sql

package relational

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countOpenRestrictionRequests = `-- name: CountOpenRestrictionRequests :one
SELECT count(*)::bigint AS n FROM restriction_requests WHERE requester = $1 AND state = 'received'
`

func (q *Queries) CountOpenRestrictionRequests(ctx context.Context, requester string) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenRestrictionRequests, requester)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const currentRestrictionVersions = `-- name: CurrentRestrictionVersions :many
SELECT v.restriction_id, v.version, v.feature,
       (CASE WHEN w.reference IS NULL THEN v."constraint"
             ELSE COALESCE(v."constraint", '{}'::jsonb) || jsonb_build_object('reference', w.reference) END)::jsonb AS "constraint",
       v.changed_by, v.changed_at, v.change_reason, v.state, v.starts_at, v.ends_at, v.msg_id, r.ansp_ref
FROM restrictions r
JOIN restriction_versions v ON v.restriction_id = r.id AND v.version = r.ansp_version
LEFT JOIN dss_constraint_writes w ON w.restriction_id = v.restriction_id AND w.ansp_version = v.version AND w.op = 'put'
WHERE r.state = $1::restriction_state
ORDER BY r.created_at DESC, r.id DESC
LIMIT $2
`

type CurrentRestrictionVersionsParams struct {
	State    RestrictionState
	PageSize int32
}

type CurrentRestrictionVersionsRow struct {
	RestrictionID string
	Version       int64
	Feature       json.RawMessage
	Constraint    json.RawMessage
	ChangedBy     string
	ChangedAt     time.Time
	ChangeReason  string
	State         RestrictionState
	StartsAt      time.Time
	EndsAt        time.Time
	MsgID         string
	AnspRef       string
}

// The current version of every restriction in the state, newest
// first (as ListRestrictions), in one read (the console snapshot, ansp audit S-4); the
// constraint as RestrictionVersion has it.
func (q *Queries) CurrentRestrictionVersions(ctx context.Context, arg CurrentRestrictionVersionsParams) ([]CurrentRestrictionVersionsRow, error) {
	rows, err := q.db.Query(ctx, currentRestrictionVersions, arg.State, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentRestrictionVersionsRow{}
	for rows.Next() {
		var i CurrentRestrictionVersionsRow
		if err := rows.Scan(
			&i.RestrictionID,
			&i.Version,
			&i.Feature,
			&i.Constraint,
			&i.ChangedBy,
			&i.ChangedAt,
			&i.ChangeReason,
			&i.State,
			&i.StartsAt,
			&i.EndsAt,
			&i.MsgID,
			&i.AnspRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const decideRestrictionRequest = `-- name: DecideRestrictionRequest :execrows
UPDATE restriction_requests SET
    state = $1, decided_by = $2, decided_at = $3,
    decision_reason = $4, restriction_id = $5
WHERE id = $6 AND state = 'received'
`

type DecideRestrictionRequestParams struct {
	State          string
	DecidedBy      *string
	DecidedAt      *time.Time
	DecisionReason *string
	RestrictionID  *string
	ID             string
}

func (q *Queries) DecideRestrictionRequest(ctx context.Context, arg DecideRestrictionRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideRestrictionRequest,
		arg.State,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.DecisionReason,
		arg.RestrictionID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dueActivations = `-- name: DueActivations :many
SELECT id FROM restrictions
WHERE state = 'planned' AND activate_at IS NOT NULL AND activate_at <= clock_timestamp()
ORDER BY activate_at
LIMIT $1
`

func (q *Queries) DueActivations(ctx context.Context, pageSize int32) ([]string, error) {
	rows, err := q.db.Query(ctx, dueActivations, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dueExpiries = `-- name: DueExpiries :many
SELECT id FROM restrictions
WHERE state = 'active' AND ends_at <= clock_timestamp()
ORDER BY ends_at
LIMIT $1
`

func (q *Queries) DueExpiries(ctx context.Context, pageSize int32) ([]string, error) {
	rows, err := q.db.Query(ctx, dueExpiries, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestrictions = `-- name: ListRestrictions :many
SELECT r.id, r.ansp_ref, r.identifier, r.uspace_airspace_id, r.zone_type,
       ST_AsGeoJSON(r.geom)::text AS geom_geojson, r.radius_m,
       r.lower_m, r.lower_ref, r.upper_m, r.upper_ref, r.starts_at, r.ends_at, r.reason_text,
       r.state, r.ansp_version, r.created_by, r.activated_by, r.ended_by, r.cancelled_by,
       r.created_at, r.activated_at, r.ended_at_actual, r.request_id, r.published_version,
       r.dss_constraint_id, r.dss_version, r.supersedes_id, r.activate_at, r.cis_version,
       v.feature, v."constraint", r.dss_state, r.dss_pending_since, r.dss_reference, r.dss_put_version
FROM restrictions r
JOIN restriction_versions v ON v.restriction_id = r.id AND v.version = r.ansp_version
WHERE ($1::restriction_state IS NULL OR r.state = $1::restriction_state)
  AND ($2::timestamptz IS NULL OR (r.starts_at <= $2::timestamptz AND r.ends_at > $2::timestamptz))
  AND ($3::float8 IS NULL OR
       ST_Intersects(CASE WHEN r.radius_m IS NULL THEN r.geom ELSE ST_Buffer(r.geom::geography, r.radius_m)::geometry END,
       CASE WHEN $3::float8 <= $4::float8
                THEN ST_MakeEnvelope($3::float8, $5::float8, $4::float8, $6::float8, 4326)
                ELSE ST_Collect(ST_MakeEnvelope($3::float8, $5::float8, 180, $6::float8, 4326),
                                ST_MakeEnvelope(-180, $5::float8, $4::float8, $6::float8, 4326))
       END))
ORDER BY r.created_at DESC, r.id DESC
LIMIT $7
`

type ListRestrictionsParams struct {
	State    *RestrictionState
	At       *time.Time
	West     *float64
	East     *float64
	South    *float64
	North    *float64
	PageSize int32
}

type ListRestrictionsRow struct {
	ID               string
	AnspRef          string
	Identifier       string
	UspaceAirspaceID string
	ZoneType         string
	GeomGeojson      string
	RadiusM          *float64
	LowerM           float64
	LowerRef         string
	UpperM           float64
	UpperRef         string
	StartsAt         time.Time
	EndsAt           time.Time
	ReasonText       string
	State            RestrictionState
	AnspVersion      int64
	CreatedBy        string
	ActivatedBy      *string
	EndedBy          *string
	CancelledBy      *string
	CreatedAt        time.Time
	ActivatedAt      *time.Time
	EndedAtActual    *time.Time
	RequestID        *string
	PublishedVersion *int64
	DssConstraintID  *uuid.UUID
	DssVersion       *int64
	SupersedesID     *string
	ActivateAt       *time.Time
	CisVersion       *string
	Feature          json.RawMessage
	Constraint       json.RawMessage
	DssState         string
	DssPendingSince  *time.Time
	DssReference     json.RawMessage
	DssPutVersion    *int64
}

func (q *Queries) ListRestrictions(ctx context.Context, arg ListRestrictionsParams) ([]ListRestrictionsRow, error) {
	rows, err := q.db.Query(ctx, listRestrictions,
		arg.State,
		arg.At,
		arg.West,
		arg.East,
		arg.South,
		arg.North,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRestrictionsRow{}
	for rows.Next() {
		var i ListRestrictionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AnspRef,
			&i.Identifier,
			&i.UspaceAirspaceID,
			&i.ZoneType,
			&i.GeomGeojson,
			&i.RadiusM,
			&i.LowerM,
			&i.LowerRef,
			&i.UpperM,
			&i.UpperRef,
			&i.StartsAt,
			&i.EndsAt,
			&i.ReasonText,
			&i.State,
			&i.AnspVersion,
			&i.CreatedBy,
			&i.ActivatedBy,
			&i.EndedBy,
			&i.CancelledBy,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.EndedAtActual,
			&i.RequestID,
			&i.PublishedVersion,
			&i.DssConstraintID,
			&i.DssVersion,
			&i.SupersedesID,
			&i.ActivateAt,
			&i.CisVersion,
			&i.Feature,
			&i.Constraint,
			&i.DssState,
			&i.DssPendingSince,
			&i.DssReference,
			&i.DssPutVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRestriction = `-- name: LockRestriction :one
SELECT r.id, r.ansp_ref, r.identifier, r.uspace_airspace_id, r.zone_type,
       ST_AsGeoJSON(r.geom)::text AS geom_geojson, r.radius_m,
       r.lower_m, r.lower_ref, r.upper_m, r.upper_ref, r.starts_at, r.ends_at, r.reason_text,
       r.state, r.ansp_version, r.created_by, r.activated_by, r.ended_by, r.cancelled_by,
       r.created_at, r.activated_at, r.ended_at_actual, r.request_id, r.published_version,
       r.dss_constraint_id, r.dss_version, r.supersedes_id, r.activate_at, r.cis_version,
       v.feature, v."constraint", r.dss_state, r.dss_pending_since, r.dss_reference, r.dss_put_version
FROM restrictions r
JOIN restriction_versions v ON v.restriction_id = r.id AND v.version = r.ansp_version
WHERE r.id = $1
FOR UPDATE OF r
`

type LockRestrictionRow struct {
	ID               string
	AnspRef          string
	Identifier       string
	UspaceAirspaceID string
	ZoneType         string
	GeomGeojson      string
	RadiusM          *float64
	LowerM           float64
	LowerRef         string
	UpperM           float64
	UpperRef         string
	StartsAt         time.Time
	EndsAt           time.Time
	ReasonText       string
	State            RestrictionState
	AnspVersion      int64
	CreatedBy        string
	ActivatedBy      *string
	EndedBy          *string
	CancelledBy      *string
	CreatedAt        time.Time
	ActivatedAt      *time.Time
	EndedAtActual    *time.Time
	RequestID        *string
	PublishedVersion *int64
	DssConstraintID  *uuid.UUID
	DssVersion       *int64
	SupersedesID     *string
	ActivateAt       *time.Time
	CisVersion       *string
	Feature          json.RawMessage
	Constraint       json.RawMessage
	DssState         string
	DssPendingSince  *time.Time
	DssReference     json.RawMessage
	DssPutVersion    *int64
}

func (q *Queries) LockRestriction(ctx context.Context, id string) (LockRestrictionRow, error) {
	row := q.db.QueryRow(ctx, lockRestriction, id)
	var i LockRestrictionRow
	err := row.Scan(
		&i.ID,
		&i.AnspRef,
		&i.Identifier,
		&i.UspaceAirspaceID,
		&i.ZoneType,
		&i.GeomGeojson,
		&i.RadiusM,
		&i.LowerM,
		&i.LowerRef,
		&i.UpperM,
		&i.UpperRef,
		&i.StartsAt,
		&i.EndsAt,
		&i.ReasonText,
		&i.State,
		&i.AnspVersion,
		&i.CreatedBy,
		&i.ActivatedBy,
		&i.EndedBy,
		&i.CancelledBy,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.EndedAtActual,
		&i.RequestID,
		&i.PublishedVersion,
		&i.DssConstraintID,
		&i.DssVersion,
		&i.SupersedesID,
		&i.ActivateAt,
		&i.CisVersion,
		&i.Feature,
		&i.Constraint,
		&i.DssState,
		&i.DssPendingSince,
		&i.DssReference,
		&i.DssPutVersion,
	)
	return i, err
}

const lockRestrictionRequest = `-- name: LockRestrictionRequest :one
SELECT id, requester, source, payload, received_at, state, decided_by, decided_at, decision_reason, restriction_id, client_ref, payload_sha256 FROM restriction_requests WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockRestrictionRequest(ctx context.Context, id string) (RestrictionRequest, error) {
	row := q.db.QueryRow(ctx, lockRestrictionRequest, id)
	var i RestrictionRequest
	err := row.Scan(
		&i.ID,
		&i.Requester,
		&i.Source,
		&i.Payload,
		&i.ReceivedAt,
		&i.State,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.RestrictionID,
		&i.ClientRef,
		&i.PayloadSha256,
	)
	return i, err
}

const markBusPublished = `-- name: MarkBusPublished :exec
UPDATE restrictions SET bus_version = GREATEST(bus_version, $1::bigint)
WHERE id = $2 AND $1::bigint <= ansp_version
`

type MarkBusPublishedParams struct {
	Version int64
	ID      string
}

func (q *Queries) MarkBusPublished(ctx context.Context, arg MarkBusPublishedParams) error {
	_, err := q.db.Exec(ctx, markBusPublished, arg.Version, arg.ID)
	return err
}

const nextRestrictionIdentifier = `-- name: NextRestrictionIdentifier :one

SELECT nextval('restriction_identifier_seq')::bigint AS seq,
       (SELECT offset_n FROM restriction_identifier_key)::bigint AS offset_n
`

type NextRestrictionIdentifierRow struct {
	Seq     int64
	OffsetN int64
}

// WP-5: the restriction state machine (internal/restriction) on the
// relational database. Every instant a judgement uses comes from the
// database's clock (clock_timestamp()), never a replica's. Geometry
// crosses as GeoJSON text; area and placement are computed on geography
// (03 conventions).
func (q *Queries) NextRestrictionIdentifier(ctx context.Context) (NextRestrictionIdentifierRow, error) {
	row := q.db.QueryRow(ctx, nextRestrictionIdentifier)
	var i NextRestrictionIdentifierRow
	err := row.Scan(&i.Seq, &i.OffsetN)
	return i, err
}

const planRestriction = `-- name: PlanRestriction :exec
INSERT INTO restrictions (
    id, ansp_ref, identifier, uspace_airspace_id, zone_type, geom, radius_m,
    lower_m, lower_ref, upper_m, upper_ref, starts_at, ends_at, reason_text,
    state, ansp_version, created_by, created_at, request_id, dss_constraint_id, supersedes_id,
    idempotency_actor, idempotency_key, idempotency_sha256, cis_version
) VALUES (
    $1, $2, $3, $4, $5,
    ST_SetSRID(ST_GeomFromGeoJSON($6::text), 4326), $7,
    $8, $9, $10, $11,
    $12, $13, $14,
    'planned', 1, $15, $16, $17, $18, $19,
    $20, $21, $22, $23
)
`

type PlanRestrictionParams struct {
	ID                string
	AnspRef           string
	Identifier        string
	UspaceAirspaceID  string
	ZoneType          string
	GeomGeojson       string
	RadiusM           *float64
	LowerM            float64
	LowerRef          string
	UpperM            float64
	UpperRef          string
	StartsAt          time.Time
	EndsAt            time.Time
	ReasonText        string
	CreatedBy         string
	CreatedAt         time.Time
	RequestID         *string
	DssConstraintID   *uuid.UUID
	SupersedesID      *string
	IdempotencyActor  *string
	IdempotencyKey    *string
	IdempotencySha256 *string
	CisVersion        *string
}

func (q *Queries) PlanRestriction(ctx context.Context, arg PlanRestrictionParams) error {
	_, err := q.db.Exec(ctx, planRestriction,
		arg.ID,
		arg.AnspRef,
		arg.Identifier,
		arg.UspaceAirspaceID,
		arg.ZoneType,
		arg.GeomGeojson,
		arg.RadiusM,
		arg.LowerM,
		arg.LowerRef,
		arg.UpperM,
		arg.UpperRef,
		arg.StartsAt,
		arg.EndsAt,
		arg.ReasonText,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.RequestID,
		arg.DssConstraintID,
		arg.SupersedesID,
		arg.IdempotencyActor,
		arg.IdempotencyKey,
		arg.IdempotencySha256,
		arg.CisVersion,
	)
	return err
}

const relateShapes = `-- name: RelateShapes :one
WITH s AS (
    SELECT
        CASE WHEN $1::float8 IS NULL
             THEN ST_SetSRID(ST_GeomFromGeoJSON($2::text), 4326)
             ELSE ST_Buffer(ST_SetSRID(ST_GeomFromGeoJSON($2::text), 4326)::geography, $1::float8)::geometry
        END AS a,
        CASE WHEN $3::float8 IS NULL
             THEN ST_SetSRID(ST_GeomFromGeoJSON($4::text), 4326)
             ELSE ST_Buffer(ST_SetSRID(ST_GeomFromGeoJSON($4::text), 4326)::geography, $3::float8)::geometry
        END AS b
)
SELECT ST_Intersects(a::geography, b::geography)::boolean AS intersects,
       ST_Covers(b, a)::boolean AS covers
FROM s
`

type RelateShapesParams struct {
	ARadiusM *float64
	AGeojson string
	BRadiusM *float64
	BGeojson string
}

type RelateShapesRow struct {
	Intersects bool
	Covers     bool
}

// a is the restriction, b the airspace part; a circle is its geodesic
// buffer. intersects on geography; covers on the planar outline in
// degrees (PostGIS has no geography ST_Covers for two polygons): the
// shapes are tens of kilometres at most, where the two agree to metres.
func (q *Queries) RelateShapes(ctx context.Context, arg RelateShapesParams) (RelateShapesRow, error) {
	row := q.db.QueryRow(ctx, relateShapes,
		arg.ARadiusM,
		arg.AGeojson,
		arg.BRadiusM,
		arg.BGeojson,
	)
	var i RelateShapesRow
	err := row.Scan(&i.Intersects, &i.Covers)
	return i, err
}

const restrictionAreaM2 = `-- name: RestrictionAreaM2 :one
SELECT ST_Area(
    CASE WHEN $1::float8 IS NULL
         THEN ST_SetSRID(ST_GeomFromGeoJSON($2::text), 4326)::geography
         ELSE ST_Buffer(ST_SetSRID(ST_GeomFromGeoJSON($2::text), 4326)::geography, $1::float8)
    END)::float8 AS area_m2
`

type RestrictionAreaM2Params struct {
	RadiusM     *float64
	GeomGeojson string
}

func (q *Queries) RestrictionAreaM2(ctx context.Context, arg RestrictionAreaM2Params) (float64, error) {
	row := q.db.QueryRow(ctx, restrictionAreaM2, arg.RadiusM, arg.GeomGeojson)
	var area_m2 float64
	err := row.Scan(&area_m2)
	return area_m2, err
}

const restrictionByIdempotency = `-- name: RestrictionByIdempotency :one
SELECT id, idempotency_sha256::text AS sha256
FROM restrictions
WHERE idempotency_actor = $1 AND idempotency_key = $2
`

type RestrictionByIdempotencyParams struct {
	Actor          *string
	IdempotencyKey *string
}

type RestrictionByIdempotencyRow struct {
	ID     string
	Sha256 string
}

func (q *Queries) RestrictionByIdempotency(ctx context.Context, arg RestrictionByIdempotencyParams) (RestrictionByIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, restrictionByIdempotency, arg.Actor, arg.IdempotencyKey)
	var i RestrictionByIdempotencyRow
	err := row.Scan(&i.ID, &i.Sha256)
	return i, err
}

const restrictionFull = `-- name: RestrictionFull :one
SELECT r.id, r.ansp_ref, r.identifier, r.uspace_airspace_id, r.zone_type,
       ST_AsGeoJSON(r.geom)::text AS geom_geojson, r.radius_m,
       r.lower_m, r.lower_ref, r.upper_m, r.upper_ref, r.starts_at, r.ends_at, r.reason_text,
       r.state, r.ansp_version, r.created_by, r.activated_by, r.ended_by, r.cancelled_by,
       r.created_at, r.activated_at, r.ended_at_actual, r.request_id, r.published_version,
       r.dss_constraint_id, r.dss_version, r.supersedes_id, r.activate_at, r.cis_version,
       v.feature, v."constraint", r.dss_state, r.dss_pending_since, r.dss_reference, r.dss_put_version
FROM restrictions r
JOIN restriction_versions v ON v.restriction_id = r.id AND v.version = r.ansp_version
WHERE r.id = $1
`

type RestrictionFullRow struct {
	ID               string
	AnspRef          string
	Identifier       string
	UspaceAirspaceID string
	ZoneType         string
	GeomGeojson      string
	RadiusM          *float64
	LowerM           float64
	LowerRef         string
	UpperM           float64
	UpperRef         string
	StartsAt         time.Time
	EndsAt           time.Time
	ReasonText       string
	State            RestrictionState
	AnspVersion      int64
	CreatedBy        string
	ActivatedBy      *string
	EndedBy          *string
	CancelledBy      *string
	CreatedAt        time.Time
	ActivatedAt      *time.Time
	EndedAtActual    *time.Time
	RequestID        *string
	PublishedVersion *int64
	DssConstraintID  *uuid.UUID
	DssVersion       *int64
	SupersedesID     *string
	ActivateAt       *time.Time
	CisVersion       *string
	Feature          json.RawMessage
	Constraint       json.RawMessage
	DssState         string
	DssPendingSince  *time.Time
	DssReference     json.RawMessage
	DssPutVersion    *int64
}

func (q *Queries) RestrictionFull(ctx context.Context, id string) (RestrictionFullRow, error) {
	row := q.db.QueryRow(ctx, restrictionFull, id)
	var i RestrictionFullRow
	err := row.Scan(
		&i.ID,
		&i.AnspRef,
		&i.Identifier,
		&i.UspaceAirspaceID,
		&i.ZoneType,
		&i.GeomGeojson,
		&i.RadiusM,
		&i.LowerM,
		&i.LowerRef,
		&i.UpperM,
		&i.UpperRef,
		&i.StartsAt,
		&i.EndsAt,
		&i.ReasonText,
		&i.State,
		&i.AnspVersion,
		&i.CreatedBy,
		&i.ActivatedBy,
		&i.EndedBy,
		&i.CancelledBy,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.EndedAtActual,
		&i.RequestID,
		&i.PublishedVersion,
		&i.DssConstraintID,
		&i.DssVersion,
		&i.SupersedesID,
		&i.ActivateAt,
		&i.CisVersion,
		&i.Feature,
		&i.Constraint,
		&i.DssState,
		&i.DssPendingSince,
		&i.DssReference,
		&i.DssPutVersion,
	)
	return i, err
}

const restrictionRequestByClientRef = `-- name: RestrictionRequestByClientRef :one
SELECT id, requester, source, payload, received_at, state, decided_by, decided_at, decision_reason, restriction_id, client_ref, payload_sha256 FROM restriction_requests WHERE requester = $1 AND client_ref = $2
`

type RestrictionRequestByClientRefParams struct {
	Requester string
	ClientRef string
}

func (q *Queries) RestrictionRequestByClientRef(ctx context.Context, arg RestrictionRequestByClientRefParams) (RestrictionRequest, error) {
	row := q.db.QueryRow(ctx, restrictionRequestByClientRef, arg.Requester, arg.ClientRef)
	var i RestrictionRequest
	err := row.Scan(
		&i.ID,
		&i.Requester,
		&i.Source,
		&i.Payload,
		&i.ReceivedAt,
		&i.State,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.RestrictionID,
		&i.ClientRef,
		&i.PayloadSha256,
	)
	return i, err
}

const restrictionSuccessor = `-- name: RestrictionSuccessor :many
SELECT id FROM restrictions
WHERE supersedes_id = $1 AND state = 'planned'
ORDER BY starts_at
LIMIT 1
`

func (q *Queries) RestrictionSuccessor(ctx context.Context, id *string) ([]string, error) {
	rows, err := q.db.Query(ctx, restrictionSuccessor, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restrictionVersion = `-- name: RestrictionVersion :one
SELECT v.restriction_id, v.version, v.feature,
       (CASE WHEN w.reference IS NULL THEN v."constraint"
             ELSE COALESCE(v."constraint", '{}'::jsonb) || jsonb_build_object('reference', w.reference) END)::jsonb AS "constraint",
       v.changed_by, v.changed_at, v.change_reason, v.state, v.starts_at, v.ends_at, v.msg_id, r.ansp_ref
FROM restriction_versions v JOIN restrictions r ON r.id = v.restriction_id
LEFT JOIN dss_constraint_writes w ON w.restriction_id = v.restriction_id AND w.ansp_version = v.version AND w.op = 'put'
WHERE v.restriction_id = $1 AND v.version = $2
`

type RestrictionVersionParams struct {
	RestrictionID string
	Version       int64
}

type RestrictionVersionRow struct {
	RestrictionID string
	Version       int64
	Feature       json.RawMessage
	Constraint    json.RawMessage
	ChangedBy     string
	ChangedAt     time.Time
	ChangeReason  string
	State         RestrictionState
	StartsAt      time.Time
	EndsAt        time.Time
	MsgID         string
	AnspRef       string
}

// constraint carries the reference the DSS accepted for this version
// (WP-9), when it did.
func (q *Queries) RestrictionVersion(ctx context.Context, arg RestrictionVersionParams) (RestrictionVersionRow, error) {
	row := q.db.QueryRow(ctx, restrictionVersion, arg.RestrictionID, arg.Version)
	var i RestrictionVersionRow
	err := row.Scan(
		&i.RestrictionID,
		&i.Version,
		&i.Feature,
		&i.Constraint,
		&i.ChangedBy,
		&i.ChangedAt,
		&i.ChangeReason,
		&i.State,
		&i.StartsAt,
		&i.EndsAt,
		&i.MsgID,
		&i.AnspRef,
	)
	return i, err
}

const unpublishedVersions = `-- name: UnpublishedVersions :many
SELECT v.restriction_id, v.version, v.feature, v."constraint", v.changed_by, v.changed_at, v.change_reason,
       v.state, v.starts_at, v.ends_at, v.msg_id, r.ansp_ref
FROM restrictions r
JOIN restriction_versions v ON v.restriction_id = r.id AND v.version > r.bus_version
WHERE r.bus_version < r.ansp_version
ORDER BY v.changed_at, v.restriction_id, v.version
LIMIT $1
`

type UnpublishedVersionsRow struct {
	RestrictionID string
	Version       int64
	Feature       json.RawMessage
	Constraint    json.RawMessage
	ChangedBy     string
	ChangedAt     time.Time
	ChangeReason  string
	State         RestrictionState
	StartsAt      time.Time
	EndsAt        time.Time
	MsgID         string
	AnspRef       string
}

func (q *Queries) UnpublishedVersions(ctx context.Context, pageSize int32) ([]UnpublishedVersionsRow, error) {
	rows, err := q.db.Query(ctx, unpublishedVersions, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnpublishedVersionsRow{}
	for rows.Next() {
		var i UnpublishedVersionsRow
		if err := rows.Scan(
			&i.RestrictionID,
			&i.Version,
			&i.Feature,
			&i.Constraint,
			&i.ChangedBy,
			&i.ChangedAt,
			&i.ChangeReason,
			&i.State,
			&i.StartsAt,
			&i.EndsAt,
			&i.MsgID,
			&i.AnspRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRestrictionState = `-- name: UpdateRestrictionState :execrows
UPDATE restrictions SET
    state = $1, ansp_version = $2, ends_at = $3,
    activate_at = $4, activated_by = $5, activated_at = $6,
    ended_by = $7, ended_at_actual = $8, cancelled_by = $9
WHERE id = $10 AND ansp_version = $11
`

type UpdateRestrictionStateParams struct {
	State         RestrictionState
	AnspVersion   int64
	EndsAt        time.Time
	ActivateAt    *time.Time
	ActivatedBy   *string
	ActivatedAt   *time.Time
	EndedBy       *string
	EndedAtActual *time.Time
	CancelledBy   *string
	ID            string
	PrevVersion   int64
}

func (q *Queries) UpdateRestrictionState(ctx context.Context, arg UpdateRestrictionStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRestrictionState,
		arg.State,
		arg.AnspVersion,
		arg.EndsAt,
		arg.ActivateAt,
		arg.ActivatedBy,
		arg.ActivatedAt,
		arg.EndedBy,
		arg.EndedAtActual,
		arg.CancelledBy,
		arg.ID,
		arg.PrevVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
