// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: restrictions.sql

package relational

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const insertRestriction = `-- name: InsertRestriction :one

INSERT INTO restrictions (
    id, ansp_ref, identifier, uspace_airspace_id, zone_type, geom, radius_m,
    lower_m, lower_ref, upper_m, upper_ref, starts_at, ends_at, reason_text,
    created_by, created_at, request_id, dss_constraint_id, supersedes_id
) VALUES (
    $1, $2, $3, $4, $5,
    ST_SetSRID(ST_GeomFromGeoJSON($6::text), 4326), $7,
    $8, $9, $10, $11,
    $12, $13, $14,
    $15, clock_timestamp(), $16, $17, $18
)
RETURNING id, ansp_version, created_at
`

type InsertRestrictionParams struct {
	ID               string
	AnspRef          string
	Identifier       string
	UspaceAirspaceID string
	ZoneType         string
	GeomGeojson      string
	RadiusM          *float64
	LowerM           float64
	LowerRef         string
	UpperM           float64
	UpperRef         string
	StartsAt         time.Time
	EndsAt           time.Time
	ReasonText       string
	CreatedBy        string
	RequestID        *string
	DssConstraintID  *uuid.UUID
	SupersedesID     *string
}

type InsertRestrictionRow struct {
	ID          string
	AnspVersion int64
	CreatedAt   time.Time
}

// WP-1: restrictions, their versions and restriction requests; WP-5
// (migration 0030) added the version's state, window and msg_id and the
// request's client_ref here, and the state transitions in
// restriction_lifecycle.sql. Geometry crosses as
// GeoJSON text (store.ParseGeometry, store.GeometryJSON).
func (q *Queries) InsertRestriction(ctx context.Context, arg InsertRestrictionParams) (InsertRestrictionRow, error) {
	row := q.db.QueryRow(ctx, insertRestriction,
		arg.ID,
		arg.AnspRef,
		arg.Identifier,
		arg.UspaceAirspaceID,
		arg.ZoneType,
		arg.GeomGeojson,
		arg.RadiusM,
		arg.LowerM,
		arg.LowerRef,
		arg.UpperM,
		arg.UpperRef,
		arg.StartsAt,
		arg.EndsAt,
		arg.ReasonText,
		arg.CreatedBy,
		arg.RequestID,
		arg.DssConstraintID,
		arg.SupersedesID,
	)
	var i InsertRestrictionRow
	err := row.Scan(&i.ID, &i.AnspVersion, &i.CreatedAt)
	return i, err
}

const insertRestrictionRequest = `-- name: InsertRestrictionRequest :one
INSERT INTO restriction_requests (id, requester, source, payload, received_at, client_ref, payload_sha256)
VALUES ($1, $2, $3, $4, $5,
        $6, $7)
RETURNING id, requester, source, payload, received_at, state, decided_by, decided_at, decision_reason, restriction_id, client_ref, payload_sha256
`

type InsertRestrictionRequestParams struct {
	ID            string
	Requester     string
	Source        string
	Payload       json.RawMessage
	ReceivedAt    time.Time
	ClientRef     string
	PayloadSha256 string
}

func (q *Queries) InsertRestrictionRequest(ctx context.Context, arg InsertRestrictionRequestParams) (RestrictionRequest, error) {
	row := q.db.QueryRow(ctx, insertRestrictionRequest,
		arg.ID,
		arg.Requester,
		arg.Source,
		arg.Payload,
		arg.ReceivedAt,
		arg.ClientRef,
		arg.PayloadSha256,
	)
	var i RestrictionRequest
	err := row.Scan(
		&i.ID,
		&i.Requester,
		&i.Source,
		&i.Payload,
		&i.ReceivedAt,
		&i.State,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.RestrictionID,
		&i.ClientRef,
		&i.PayloadSha256,
	)
	return i, err
}

const insertRestrictionVersion = `-- name: InsertRestrictionVersion :exec
INSERT INTO restriction_versions (restriction_id, version, feature, "constraint", changed_by, changed_at, change_reason,
                                  state, starts_at, ends_at, msg_id)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9, $10, $11)
`

type InsertRestrictionVersionParams struct {
	RestrictionID   string
	Version         int64
	Feature         json.RawMessage
	F3548Constraint json.RawMessage
	ChangedBy       string
	ChangedAt       time.Time
	ChangeReason    string
	State           RestrictionState
	StartsAt        time.Time
	EndsAt          time.Time
	MsgID           string
}

func (q *Queries) InsertRestrictionVersion(ctx context.Context, arg InsertRestrictionVersionParams) error {
	_, err := q.db.Exec(ctx, insertRestrictionVersion,
		arg.RestrictionID,
		arg.Version,
		arg.Feature,
		arg.F3548Constraint,
		arg.ChangedBy,
		arg.ChangedAt,
		arg.ChangeReason,
		arg.State,
		arg.StartsAt,
		arg.EndsAt,
		arg.MsgID,
	)
	return err
}

const restrictionByAnspRef = `-- name: RestrictionByAnspRef :one
SELECT id, ansp_version, state FROM restrictions WHERE ansp_ref = $1
`

type RestrictionByAnspRefRow struct {
	ID          string
	AnspVersion int64
	State       RestrictionState
}

func (q *Queries) RestrictionByAnspRef(ctx context.Context, anspRef string) (RestrictionByAnspRefRow, error) {
	row := q.db.QueryRow(ctx, restrictionByAnspRef, anspRef)
	var i RestrictionByAnspRefRow
	err := row.Scan(&i.ID, &i.AnspVersion, &i.State)
	return i, err
}

const restrictionByID = `-- name: RestrictionByID :one
SELECT id, ansp_ref, identifier, uspace_airspace_id, zone_type,
       ST_AsGeoJSON(geom)::text AS geom_geojson, radius_m,
       lower_m, lower_ref, upper_m, upper_ref, starts_at, ends_at, reason_text,
       state, ansp_version, created_by, activated_by, ended_by, cancelled_by,
       created_at, activated_at, ended_at_actual, request_id, published_version,
       dss_constraint_id, dss_ovn, dss_version, supersedes_id
FROM restrictions WHERE id = $1
`

type RestrictionByIDRow struct {
	ID               string
	AnspRef          string
	Identifier       string
	UspaceAirspaceID string
	ZoneType         string
	GeomGeojson      string
	RadiusM          *float64
	LowerM           float64
	LowerRef         string
	UpperM           float64
	UpperRef         string
	StartsAt         time.Time
	EndsAt           time.Time
	ReasonText       string
	State            RestrictionState
	AnspVersion      int64
	CreatedBy        string
	ActivatedBy      *string
	EndedBy          *string
	CancelledBy      *string
	CreatedAt        time.Time
	ActivatedAt      *time.Time
	EndedAtActual    *time.Time
	RequestID        *string
	PublishedVersion *int64
	DssConstraintID  *uuid.UUID
	DssOvn           *string
	DssVersion       *int64
	SupersedesID     *string
}

func (q *Queries) RestrictionByID(ctx context.Context, id string) (RestrictionByIDRow, error) {
	row := q.db.QueryRow(ctx, restrictionByID, id)
	var i RestrictionByIDRow
	err := row.Scan(
		&i.ID,
		&i.AnspRef,
		&i.Identifier,
		&i.UspaceAirspaceID,
		&i.ZoneType,
		&i.GeomGeojson,
		&i.RadiusM,
		&i.LowerM,
		&i.LowerRef,
		&i.UpperM,
		&i.UpperRef,
		&i.StartsAt,
		&i.EndsAt,
		&i.ReasonText,
		&i.State,
		&i.AnspVersion,
		&i.CreatedBy,
		&i.ActivatedBy,
		&i.EndedBy,
		&i.CancelledBy,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.EndedAtActual,
		&i.RequestID,
		&i.PublishedVersion,
		&i.DssConstraintID,
		&i.DssOvn,
		&i.DssVersion,
		&i.SupersedesID,
	)
	return i, err
}

const restrictionRequestByID = `-- name: RestrictionRequestByID :one
SELECT id, requester, source, payload, received_at, state, decided_by, decided_at, decision_reason, restriction_id, client_ref, payload_sha256 FROM restriction_requests WHERE id = $1
`

func (q *Queries) RestrictionRequestByID(ctx context.Context, id string) (RestrictionRequest, error) {
	row := q.db.QueryRow(ctx, restrictionRequestByID, id)
	var i RestrictionRequest
	err := row.Scan(
		&i.ID,
		&i.Requester,
		&i.Source,
		&i.Payload,
		&i.ReceivedAt,
		&i.State,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.RestrictionID,
		&i.ClientRef,
		&i.PayloadSha256,
	)
	return i, err
}

const restrictionVersions = `-- name: RestrictionVersions :many
SELECT v.restriction_id, v.version, v.feature, v."constraint", v.changed_by, v.changed_at, v.change_reason,
       v.state, v.starts_at, v.ends_at, v.msg_id, r.ansp_ref
FROM restriction_versions v JOIN restrictions r ON r.id = v.restriction_id
WHERE v.restriction_id = $1
ORDER BY v.version
LIMIT $2
`

type RestrictionVersionsParams struct {
	RestrictionID string
	PageSize      int32
}

type RestrictionVersionsRow struct {
	RestrictionID string
	Version       int64
	Feature       json.RawMessage
	Constraint    json.RawMessage
	ChangedBy     string
	ChangedAt     time.Time
	ChangeReason  string
	State         RestrictionState
	StartsAt      time.Time
	EndsAt        time.Time
	MsgID         string
	AnspRef       string
}

func (q *Queries) RestrictionVersions(ctx context.Context, arg RestrictionVersionsParams) ([]RestrictionVersionsRow, error) {
	rows, err := q.db.Query(ctx, restrictionVersions, arg.RestrictionID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RestrictionVersionsRow{}
	for rows.Next() {
		var i RestrictionVersionsRow
		if err := rows.Scan(
			&i.RestrictionID,
			&i.Version,
			&i.Feature,
			&i.Constraint,
			&i.ChangedBy,
			&i.ChangedAt,
			&i.ChangeReason,
			&i.State,
			&i.StartsAt,
			&i.EndsAt,
			&i.MsgID,
			&i.AnspRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
