// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package relational

import (
	"context"

	"github.com/google/uuid"
)

const listSourceControls = `-- name: ListSourceControls :many
SELECT source_type, instance_id, enabled, reason, actor, changed_at, version, epoch
FROM source_controls
ORDER BY source_type, instance_id NULLS FIRST
LIMIT $1
`

func (q *Queries) ListSourceControls(ctx context.Context, pageSize int32) ([]SourceControl, error) {
	rows, err := q.db.Query(ctx, listSourceControls, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SourceControl{}
	for rows.Next() {
		var i SourceControl
		if err := rows.Scan(
			&i.SourceType,
			&i.InstanceID,
			&i.Enabled,
			&i.Reason,
			&i.Actor,
			&i.ChangedAt,
			&i.Version,
			&i.Epoch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxSourceControlVersion = `-- name: MaxSourceControlVersion :one
SELECT COALESCE(max(version), 0)::bigint AS version FROM source_controls
`

func (q *Queries) MaxSourceControlVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, maxSourceControlVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const sourceControlEpoch = `-- name: SourceControlEpoch :one

SELECT epoch FROM source_control_epoch WHERE singleton
`

// WP-1: source_controls, for WP-6's internal/sources writer and its
// periodic republish (LESSONS B-09).
func (q *Queries) SourceControlEpoch(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, sourceControlEpoch)
	var epoch uuid.UUID
	err := row.Scan(&epoch)
	return epoch, err
}

const upsertSourceControl = `-- name: UpsertSourceControl :one
INSERT INTO source_controls (source_type, instance_id, enabled, reason, actor, changed_at, version, epoch)
VALUES (
    $1, $2, $3, $4, $5,
    clock_timestamp(), nextval('source_controls_version_seq'),
    (SELECT epoch FROM source_control_epoch WHERE singleton)
)
ON CONFLICT (source_type, instance_id) DO UPDATE SET
    enabled = EXCLUDED.enabled, reason = EXCLUDED.reason, actor = EXCLUDED.actor,
    changed_at = EXCLUDED.changed_at, version = EXCLUDED.version, epoch = EXCLUDED.epoch
RETURNING source_type, instance_id, enabled, reason, actor, changed_at, version, epoch
`

type UpsertSourceControlParams struct {
	SourceType string
	InstanceID *string
	Enabled    bool
	Reason     string
	Actor      string
}

// One switch, with the next version of the sequence and the epoch of
// this database; the caller holds the writers' advisory lock (B-09).
func (q *Queries) UpsertSourceControl(ctx context.Context, arg UpsertSourceControlParams) (SourceControl, error) {
	row := q.db.QueryRow(ctx, upsertSourceControl,
		arg.SourceType,
		arg.InstanceID,
		arg.Enabled,
		arg.Reason,
		arg.Actor,
	)
	var i SourceControl
	err := row.Scan(
		&i.SourceType,
		&i.InstanceID,
		&i.Enabled,
		&i.Reason,
		&i.Actor,
		&i.ChangedAt,
		&i.Version,
		&i.Epoch,
	)
	return i, err
}
