// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store.sql

package relational

import (
	"context"
	"time"
)

const advisoryXactLock = `-- name: AdvisoryXactLock :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// Blocks until the transaction-scoped advisory lock key is held; it is
// released at commit or rollback. Bounded by lock_timeout.
func (q *Queries) AdvisoryXactLock(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, advisoryXactLock, key)
	return err
}

const dBNow = `-- name: DBNow :one
SELECT clock_timestamp()::timestamptz AS now
`

// The database clock (not the transaction start): expiry, audit time
// and every other stored instant come from here, never from a process
// clock.
func (q *Queries) DBNow(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, dBNow)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}

const schemaVersion = `-- name: SchemaVersion :one

SELECT version_id FROM goose_db_version_relational
WHERE is_applied ORDER BY id DESC LIMIT 1
`

// WP-1: the schema check, the clock and advisory locks.
// The version the relational tree is at: goose v3 deletes the row of a
// rolled-back migration, so the newest applied row is the version.
func (q *Queries) SchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, schemaVersion)
	var version_id int64
	err := row.Scan(&version_id)
	return version_id, err
}
