#!/usr/bin/env bash
# Development only: writes one NKey per process (api, manned-adapter,
# manned-feed) and the NATS server configuration that admits exactly
# those three, into local/nats/ (git-ignored). The keys are generated by
# nsc in the pinned nats-box image, never committed, and kept when they
# already exist, so a second run changes nothing. Production credentials
# belong to the deployment (docs/PLAN.md section 11).
set -euo pipefail
cd "$(dirname "$0")/.."

NATS_BOX_IMAGE="${NATS_BOX_IMAGE:-natsio/nats-box:0.18.0}"
dir=local/nats
mkdir -p "$dir"

users=""
for p in api manned-adapter manned-feed; do
  seed="$dir/$p.nk"
  pub="$dir/$p.pub"
  if [ ! -s "$seed" ] || [ ! -s "$pub" ]; then
    # nsc prints the seed, then the public key.
    out="$(docker run --rm --entrypoint nsc "$NATS_BOX_IMAGE" generate nkey --user 2>/dev/null)"
    s="$(sed -n 1p <<<"$out" | tr -d '\r')"
    u="$(sed -n 2p <<<"$out" | tr -d '\r')"
    if [[ "$s" != SU* || "$u" != U* ]]; then
      echo "nats-creds: nsc did not return a user key pair for $p"
      exit 1
    fi
    printf '%s\n' "$s" > "$seed"
    printf '%s\n' "$u" > "$pub"
    echo "nats-creds: wrote $seed"
  else
    echo "nats-creds: kept $seed"
  fi
  # The distroless image runs as nonroot and reads the seed through a
  # bind mount; local/ is git-ignored and development only.
  chmod 0644 "$seed"
  users+="    { nkey: \"$(tr -d '\r\n' < "$pub")\" } # $p"$'\n'
done

cat > "$dir/nats.conf" <<CONF
# Generated by scripts/nats-creds.sh for development; never committed.
port: 4222
http_port: 8222
jetstream { store_dir: /data }
authorization {
  users = [
${users}  ]
}
CONF
echo "nats-creds: wrote $dir/nats.conf (users api, manned-adapter, manned-feed)"
