// Command opsgen writes api/gen/operations.gen.go: every operation of
// api/openapi.yaml with its method, Go 1.22 mux pattern, tag and the
// x-process, x-spec, x-auth and x-websocket extensions, so that the
// server enforces the access rule the contract states (internal/auth
// ParseAccess) without parsing YAML at run time. It refuses an
// operation without operationId, x-process, x-spec or x-auth, so a
// route cannot be generated without its access rule. With -stub it also
// writes the contract tests' strict-server stub (api/stub_gen_test.go),
// which answers every operation with its example. Run by go generate in
// api/gen after oapi-codegen.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"net/http"
	"os"
	"slices"
	"strconv"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// methods in the order oapi-codegen registers them is irrelevant here;
// the output is sorted by path, then by this order.
var methods = []string{http.MethodGet, http.MethodHead, http.MethodPost, http.MethodPut, http.MethodPatch, http.MethodDelete}

type operation struct {
	id, method, path, tag, process, spec, auth string
	websocket                                  bool
}

func main() {
	spec := flag.String("spec", "../openapi.yaml", "the OpenAPI file")
	out := flag.String("o", "operations.gen.go", "the Go file to write")
	stub := flag.String("stub", "", "the contract tests' stub file to write, if any")
	flag.Parse()
	if err := run(*spec, *out, *stub); err != nil {
		fmt.Fprintln(os.Stderr, "opsgen:", err)
		os.Exit(1) //nolint:forbidigo // a generator run by go generate exits non-zero on a refused spec
	}
}

func run(spec, out, stub string) error {
	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	doc, err := loader.LoadFromFile(spec)
	if err != nil {
		return err
	}
	ops, err := collect(doc)
	if err != nil {
		return err
	}
	src, err := render(ops)
	if err != nil {
		return err
	}
	if err := os.WriteFile(out, src, 0o600); err != nil {
		return err
	}
	if stub == "" {
		return nil
	}
	src, err = renderStub(ops)
	if err != nil {
		return err
	}
	return os.WriteFile(stub, src, 0o600)
}

func extString(ext map[string]any, key string) (string, bool) {
	v, ok := ext[key]
	if !ok {
		return "", false
	}
	s, ok := v.(string)
	return s, ok && s != ""
}

func collect(doc *openapi3.T) ([]operation, error) {
	var ops []operation
	var errs []error
	paths := doc.Paths.InMatchingOrder()
	slices.Sort(paths)
	for _, path := range paths {
		item := doc.Paths.Value(path)
		for _, method := range methods {
			op := item.GetOperation(method)
			if op == nil {
				continue
			}
			o := operation{id: op.OperationID, method: method, path: path}
			if o.id == "" {
				errs = append(errs, fmt.Errorf("%s %s: no operationId", method, path))
			}
			if len(op.Tags) != 1 {
				errs = append(errs, fmt.Errorf("%s %s: exactly one tag is required", method, path))
			} else {
				o.tag = op.Tags[0]
			}
			var ok bool
			for key, dst := range map[string]*string{"x-process": &o.process, "x-spec": &o.spec, "x-auth": &o.auth} {
				if *dst, ok = extString(op.Extensions, key); !ok {
					errs = append(errs, fmt.Errorf("%s %s: %s is missing or not a string", method, path, key))
				}
			}
			if v, present := op.Extensions["x-websocket"]; present {
				b, isBool := v.(bool)
				if !isBool {
					errs = append(errs, fmt.Errorf("%s %s: x-websocket is not a boolean", method, path))
				}
				o.websocket = b
			}
			ops = append(ops, o)
		}
	}
	return ops, errors.Join(errs...)
}

func render(ops []operation) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(`// Code generated by api/internal/opsgen from api/openapi.yaml. DO NOT EDIT.

package gen

import "context"

// Operation is one operation of api/openapi.yaml with the extensions the
// server enforces: Process (x-process: api, manned-feed, or each for the
// health endpoints every process serves), Spec (x-spec), Auth (x-auth,
// parsed by internal/auth ParseAccess) and WebSocket (x-websocket).
// Pattern is the Go 1.22 ServeMux pattern the generated router
// registers.
type Operation struct {
	ID        string
	Method    string
	Path      string
	Pattern   string
	Tag       string
	Process   string
	Spec      string
	Auth      string
	WebSocket bool
}

// Operations is every operation of api/openapi.yaml, by path and method.
var Operations = []Operation{
`)
	for _, o := range ops {
		fmt.Fprintf(&b, "\t{ID: %s, Method: %s, Path: %s, Pattern: %s, Tag: %s, Process: %s, Spec: %s, Auth: %s, WebSocket: %t},\n",
			strconv.Quote(o.id), strconv.Quote(o.method), strconv.Quote(o.path), strconv.Quote(o.method+" "+o.path),
			strconv.Quote(o.tag), strconv.Quote(o.process), strconv.Quote(o.spec), strconv.Quote(o.auth), o.websocket)
	}
	b.WriteString(`}

// NotImplementedError is what Unimplemented answers: the operation is in
// the contract and a later work package serves it.
type NotImplementedError struct{ Operation string }

func (e *NotImplementedError) Error() string { return e.Operation + " is not implemented" }

// Unimplemented answers every operation of the strict server with a
// *NotImplementedError; a work package embeds it and overrides the
// operations it serves.
type Unimplemented struct{}

var _ StrictServerInterface = Unimplemented{}

`)
	for _, o := range ops {
		name := strings.ToUpper(o.id[:1]) + o.id[1:]
		fmt.Fprintf(&b, "// %s answers %s %s with a *NotImplementedError.\n", name, o.method, o.path)
		fmt.Fprintf(&b, "func (Unimplemented) %s(context.Context, %sRequestObject) (%sResponseObject, error) {\n\treturn nil, &NotImplementedError{Operation: %s}\n}\n\n",
			name, name, name, strconv.Quote(o.id))
	}
	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format: %w", err)
	}
	return bytes.ReplaceAll(src, []byte("\r\n"), []byte("\n")), nil
}

// renderStub writes the strict-server stub of the contract tests: every
// operation hands its request object to answer and returns the canned
// response answer gives, which implements every response interface.
func renderStub(ops []operation) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(`// Code generated by api/internal/opsgen from api/openapi.yaml. DO NOT EDIT.

package api_test

import (
	"context"
	"net/http"

	"github.com/rootxkit/uspace-ansp/api/gen"
)

// exampleStub is a strict server whose every operation returns
// answer(operationId, request).
type exampleStub struct {
	answer func(op string, request any) canned
}

var _ gen.StrictServerInterface = exampleStub{}

`)
	for _, o := range ops {
		name := strings.ToUpper(o.id[:1]) + o.id[1:]
		fmt.Fprintf(&b, "func (s exampleStub) %s(_ context.Context, request gen.%sRequestObject) (gen.%sResponseObject, error) {%sreturn s.answer(%s, request), nil%s}%s",
			name, name, name, nl+"\t", strconv.Quote(o.id), nl, nl+nl)
		fmt.Fprintf(&b, "func (c canned) Visit%sResponse(w http.ResponseWriter) error { return c.visit(w) }%s", name, nl+nl)
	}
	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format: %w", err)
	}
	return bytes.ReplaceAll(src, []byte("\r"+nl), []byte(nl)), nil
}

// nl is a line feed.
const nl = "\n"
