// Code generated by api/internal/opsgen from api/openapi.yaml. DO NOT EDIT.

package api_test

import (
	"context"
	"net/http"

	"github.com/rootxkit/uspace-ansp/api/gen"
)

// exampleStub is a strict server whose every operation returns
// answer(operationId, request).
type exampleStub struct {
	answer func(op string, request any) canned
}

var _ gen.StrictServerInterface = exampleStub{}

func (s exampleStub) GetJwks(_ context.Context, request gen.GetJwksRequestObject) (gen.GetJwksResponseObject, error) {
	return s.answer("getJwks", request), nil
}

func (c canned) VisitGetJwksResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) GetHealthz(_ context.Context, request gen.GetHealthzRequestObject) (gen.GetHealthzResponseObject, error) {
	return s.answer("getHealthz", request), nil
}

func (c canned) VisitGetHealthzResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) GetMetrics(_ context.Context, request gen.GetMetricsRequestObject) (gen.GetMetricsResponseObject, error) {
	return s.answer("getMetrics", request), nil
}

func (c canned) VisitGetMetricsResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) GetReadyz(_ context.Context, request gen.GetReadyzRequestObject) (gen.GetReadyzResponseObject, error) {
	return s.answer("getReadyz", request), nil
}

func (c canned) VisitGetReadyzResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) GetConstraintDetails(_ context.Context, request gen.GetConstraintDetailsRequestObject) (gen.GetConstraintDetailsResponseObject, error) {
	return s.answer("getConstraintDetails", request), nil
}

func (c canned) VisitGetConstraintDetailsResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) ListAdapters(_ context.Context, request gen.ListAdaptersRequestObject) (gen.ListAdaptersResponseObject, error) {
	return s.answer("listAdapters", request), nil
}

func (c canned) VisitListAdaptersResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) GetAdapter(_ context.Context, request gen.GetAdapterRequestObject) (gen.GetAdapterResponseObject, error) {
	return s.answer("getAdapter", request), nil
}

func (c canned) VisitGetAdapterResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) ListAudit(_ context.Context, request gen.ListAuditRequestObject) (gen.ListAuditResponseObject, error) {
	return s.answer("listAudit", request), nil
}

func (c canned) VisitListAuditResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) Login(_ context.Context, request gen.LoginRequestObject) (gen.LoginResponseObject, error) {
	return s.answer("login", request), nil
}

func (c canned) VisitLoginResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) Logout(_ context.Context, request gen.LogoutRequestObject) (gen.LogoutResponseObject, error) {
	return s.answer("logout", request), nil
}

func (c canned) VisitLogoutResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) GetMe(_ context.Context, request gen.GetMeRequestObject) (gen.GetMeResponseObject, error) {
	return s.answer("getMe", request), nil
}

func (c canned) VisitGetMeResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) VerifyMfa(_ context.Context, request gen.VerifyMfaRequestObject) (gen.VerifyMfaResponseObject, error) {
	return s.answer("verifyMfa", request), nil
}

func (c canned) VisitVerifyMfaResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) ReceiveCisNotification(_ context.Context, request gen.ReceiveCisNotificationRequestObject) (gen.ReceiveCisNotificationResponseObject, error) {
	return s.answer("receiveCisNotification", request), nil
}

func (c canned) VisitReceiveCisNotificationResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) ListCoordinationInbox(_ context.Context, request gen.ListCoordinationInboxRequestObject) (gen.ListCoordinationInboxResponseObject, error) {
	return s.answer("listCoordinationInbox", request), nil
}

func (c canned) VisitListCoordinationInboxResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) AcknowledgeCoordinationNotice(_ context.Context, request gen.AcknowledgeCoordinationNoticeRequestObject) (gen.AcknowledgeCoordinationNoticeResponseObject, error) {
	return s.answer("acknowledgeCoordinationNotice", request), nil
}

func (c canned) VisitAcknowledgeCoordinationNoticeResponse(w http.ResponseWriter) error {
	return c.visit(w)
}

func (s exampleStub) SubmitCoordinationNotice(_ context.Context, request gen.SubmitCoordinationNoticeRequestObject) (gen.SubmitCoordinationNoticeResponseObject, error) {
	return s.answer("submitCoordinationNotice", request), nil
}

func (c canned) VisitSubmitCoordinationNoticeResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) GetCoordinationNotice(_ context.Context, request gen.GetCoordinationNoticeRequestObject) (gen.GetCoordinationNoticeResponseObject, error) {
	return s.answer("getCoordinationNotice", request), nil
}

func (c canned) VisitGetCoordinationNoticeResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) StreamCoordination(_ context.Context, request gen.StreamCoordinationRequestObject) (gen.StreamCoordinationResponseObject, error) {
	return s.answer("streamCoordination", request), nil
}

func (c canned) VisitStreamCoordinationResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) GetMannedTrafficSnapshot(_ context.Context, request gen.GetMannedTrafficSnapshotRequestObject) (gen.GetMannedTrafficSnapshotResponseObject, error) {
	return s.answer("getMannedTrafficSnapshot", request), nil
}

func (c canned) VisitGetMannedTrafficSnapshotResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) StreamMannedTraffic(_ context.Context, request gen.StreamMannedTrafficRequestObject) (gen.StreamMannedTrafficResponseObject, error) {
	return s.answer("streamMannedTraffic", request), nil
}

func (c canned) VisitStreamMannedTrafficResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) CreateOccurrence(_ context.Context, request gen.CreateOccurrenceRequestObject) (gen.CreateOccurrenceResponseObject, error) {
	return s.answer("createOccurrence", request), nil
}

func (c canned) VisitCreateOccurrenceResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) GetPolicy(_ context.Context, request gen.GetPolicyRequestObject) (gen.GetPolicyResponseObject, error) {
	return s.answer("getPolicy", request), nil
}

func (c canned) VisitGetPolicyResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) PutPolicy(_ context.Context, request gen.PutPolicyRequestObject) (gen.PutPolicyResponseObject, error) {
	return s.answer("putPolicy", request), nil
}

func (c canned) VisitPutPolicyResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) CreateRestrictionRequest(_ context.Context, request gen.CreateRestrictionRequestRequestObject) (gen.CreateRestrictionRequestResponseObject, error) {
	return s.answer("createRestrictionRequest", request), nil
}

func (c canned) VisitCreateRestrictionRequestResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) GetRestrictionRequest(_ context.Context, request gen.GetRestrictionRequestRequestObject) (gen.GetRestrictionRequestResponseObject, error) {
	return s.answer("getRestrictionRequest", request), nil
}

func (c canned) VisitGetRestrictionRequestResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) AcceptRestrictionRequest(_ context.Context, request gen.AcceptRestrictionRequestRequestObject) (gen.AcceptRestrictionRequestResponseObject, error) {
	return s.answer("acceptRestrictionRequest", request), nil
}

func (c canned) VisitAcceptRestrictionRequestResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) DeclineRestrictionRequest(_ context.Context, request gen.DeclineRestrictionRequestRequestObject) (gen.DeclineRestrictionRequestResponseObject, error) {
	return s.answer("declineRestrictionRequest", request), nil
}

func (c canned) VisitDeclineRestrictionRequestResponse(w http.ResponseWriter) error {
	return c.visit(w)
}

func (s exampleStub) ListRestrictions(_ context.Context, request gen.ListRestrictionsRequestObject) (gen.ListRestrictionsResponseObject, error) {
	return s.answer("listRestrictions", request), nil
}

func (c canned) VisitListRestrictionsResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) CreateRestriction(_ context.Context, request gen.CreateRestrictionRequestObject) (gen.CreateRestrictionResponseObject, error) {
	return s.answer("createRestriction", request), nil
}

func (c canned) VisitCreateRestrictionResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) StreamRestrictions(_ context.Context, request gen.StreamRestrictionsRequestObject) (gen.StreamRestrictionsResponseObject, error) {
	return s.answer("streamRestrictions", request), nil
}

func (c canned) VisitStreamRestrictionsResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) GetRestriction(_ context.Context, request gen.GetRestrictionRequestObject) (gen.GetRestrictionResponseObject, error) {
	return s.answer("getRestriction", request), nil
}

func (c canned) VisitGetRestrictionResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) ActivateRestriction(_ context.Context, request gen.ActivateRestrictionRequestObject) (gen.ActivateRestrictionResponseObject, error) {
	return s.answer("activateRestriction", request), nil
}

func (c canned) VisitActivateRestrictionResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) CancelRestriction(_ context.Context, request gen.CancelRestrictionRequestObject) (gen.CancelRestrictionResponseObject, error) {
	return s.answer("cancelRestriction", request), nil
}

func (c canned) VisitCancelRestrictionResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) EndRestriction(_ context.Context, request gen.EndRestrictionRequestObject) (gen.EndRestrictionResponseObject, error) {
	return s.answer("endRestriction", request), nil
}

func (c canned) VisitEndRestrictionResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) ExtendRestriction(_ context.Context, request gen.ExtendRestrictionRequestObject) (gen.ExtendRestrictionResponseObject, error) {
	return s.answer("extendRestriction", request), nil
}

func (c canned) VisitExtendRestrictionResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) ListRestrictionVersions(_ context.Context, request gen.ListRestrictionVersionsRequestObject) (gen.ListRestrictionVersionsResponseObject, error) {
	return s.answer("listRestrictionVersions", request), nil
}

func (c canned) VisitListRestrictionVersionsResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) GetRestrictionVersion(_ context.Context, request gen.GetRestrictionVersionRequestObject) (gen.GetRestrictionVersionResponseObject, error) {
	return s.answer("getRestrictionVersion", request), nil
}

func (c canned) VisitGetRestrictionVersionResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) ListSources(_ context.Context, request gen.ListSourcesRequestObject) (gen.ListSourcesResponseObject, error) {
	return s.answer("listSources", request), nil
}

func (c canned) VisitListSourcesResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) SetSourceControl(_ context.Context, request gen.SetSourceControlRequestObject) (gen.SetSourceControlResponseObject, error) {
	return s.answer("setSourceControl", request), nil
}

func (c canned) VisitSetSourceControlResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) ListUsers(_ context.Context, request gen.ListUsersRequestObject) (gen.ListUsersResponseObject, error) {
	return s.answer("listUsers", request), nil
}

func (c canned) VisitListUsersResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) CreateUser(_ context.Context, request gen.CreateUserRequestObject) (gen.CreateUserResponseObject, error) {
	return s.answer("createUser", request), nil
}

func (c canned) VisitCreateUserResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) DisableUser(_ context.Context, request gen.DisableUserRequestObject) (gen.DisableUserResponseObject, error) {
	return s.answer("disableUser", request), nil
}

func (c canned) VisitDisableUserResponse(w http.ResponseWriter) error { return c.visit(w) }

func (s exampleStub) ResetUserMfa(_ context.Context, request gen.ResetUserMfaRequestObject) (gen.ResetUserMfaResponseObject, error) {
	return s.answer("resetUserMfa", request), nil
}

func (c canned) VisitResetUserMfaResponse(w http.ResponseWriter) error { return c.visit(w) }
