// Package replay is the recorded-frame adapter the lab's "ANSP feed"
// simulator drives: an NDJSON file whose first line is a
// replay/header/v1 header saying the file is synthetic and giving its
// source class, followed by track/manned/v1 records with their original
// ts. It replays at wall speed (or Speed), keeping the records' spacing,
// and loops with the times shifted forward so the replayed clock never
// runs back. It refuses to start unless ANSP_ADAPTER_REPLAY_ALLOWED is
// true (never by default, 06 T11), unless the header says synthetic
// (CLAUDE.md rule 11), or at a speed outside (0, 1000]; the status shows
// replay. Records are bounded by max_record_bytes; a record that does not
// parse is refused and counted; nothing panics (FuzzReplayFrame). The
// synthetic files are testdata/replay/, generated by this package's
// tests.
package replay
